### ISSUE TITLE
Cmd+tab doesnt work in vscode

### ISSUE THREAD

**Issue by medyagh** [rbreaves/kinto#116]
hi first of all thank you for this great idea and good project ! I love it.

one issue I faced, is when I am on vscode (visual studio code)
the cmd+tab doesnt work.

I am on ubuntu 20.04 and I use it in iMac with Mac keyboard.

**Comment by rbreaves** [comment]
I'm surprised, can you make sure you're on the latest? I just uninstalled it completely and re-installed on the latest commit of 08e5a01.

Some changes are happening to Cmd+Tab, primarily to resolve things on KDE and it might actually result in this project becoming a little bit simpler for others to contribute (shortcut keys) to if I can fork [xkeysnail](https://github.com/mooz/xkeysnail) to support shortcut keys that need to be held - specifically Cmd+Tab.

Another feature that I'd like to integrate into it from Kinto is the caret status check feature so that the keymaps for specific apps can change as needed based on the caret status as well. Ultimately I do not know if xkeysnail can be as reliable as what xkb tends to be, once set right, but if it is then xkeysnail may be an even better backend for Kinto to run off of.

**Comment by medyagh** [comment]
thanks for the response, @rbreaves , I tried pulling and running setup agian but that didn't help, but I did not try uninstalling first.

**Comment by medyagh** [comment]
ok I confirm, uninstalling it and installing the latest version on 

```
commit 08e5a01a89938630029a2b6541ea9b9ca07af639 (HEAD -> master, origin/master, origin/HEAD)
Merge: 4cbc665 5e0fcca
Author: Ben Reaves <rbreaves@gmail.com>
Date:   Wed Apr 15 12:55:23 2020 -0500

    Merge pull request #114 from rbreaves/dev
    

```

fixed it

thank you very much @rbreaves and please keep up this great project

**Comment by rbreaves** [comment]
Np! Also a pretty major update will be on the way in the next few to several days I suppose. I just knocked out one of the big issues I was having with xkeysnail, it is now releasing modifier keys when it should. Only thing that remains is the caret check, but that is relatively minor. I will be looking to update the installer to give people the choice of using either the kintox11 method or xkeysnail before I re-implement the caret check.

In my opinion xkeysnail will be the way forward because the config file is far simpler to setup, manage and modify for everyone involved and after working out the key/modifier release issues it appears to work reliably.

A preview of what the config file to come is going to look like under xkeysnail.
https://github.com/rbreaves/kinto/blob/dev/xkeysnail/kinto.py

I'm closing this ticket, but let me know if there's anything else.
