### ISSUE TITLE
Normal apps without swapping Alt, only swapping Ctrl and Alt

### ISSUE THREAD

**Issue by saravanabalagi** [rbreaves/kinto#124]
Is it possible to do 
```
Normal apps - Win/Super → Ctrl, Ctrl → Win/Super (and implied Alt → Alt)
```
out of the box in Kinto?

**Comment by rbreaves** [comment]
There's no out of the box menu type option during the setup to do that configuration, it doesn't really align with macOS, assuming you are talking about a standard Windows keyboard layout.

Of course if you are talking about a mac keyboard then that is exactly what it does.

It's probably easiest to reconfigure the newer xkeysnail implementation, which is now on dev to do what you want. (although xkb is just a matter of figuring out the correct option name and updating the keymap accordingly - but that could take some trial and error to find the right option).

Also xkeysnails implementation is slightly different - it can detect the difference between left and right control better than xkb can and due to that I can map things a little differently during terminal usage for simplicity. XKB actually does Super -> Ctrl+Shift during term usage, but xkeysnail does Right Ctrl -> Ctrl+Shift (on specific keys).

dev branch
./xkeysnail-config/kinto.py
```
...
define_conditional_modmap(lambda wm_class: wm_class not in ("Gnome-terminal","konsole","io.elementary.terminal","terminator","sakura","guake","tilda","xterm","eterm","kitty"),{
...

    # # Default Mac/Win
    # ALT Untoched
    # Key.LEFT_META: Key.RIGHT_CTRL,    # WinMac
    # Key.LEFT_CTRL: Key.LEFT_META,   # WinMac
    # Key.RIGHT_META: Key.RIGHT_CTRL,  # WinMac
    # Key.RIGHT_CTRL: Key.RIGHT_META, # WinMac
...

define_conditional_modmap(re.compile("Gnome-terminal|konsole|io.elementary.terminal|terminator|sakura|guake|tilda|xterm|eterm|kitty"), {
...
    # # Default Mac/Win
    # Alt untouched
    # Key.LEFT_META: Key.RIGHT_CTRL,    # WinMac
    # Left Ctrl untoched
    # Key.RIGHT_META: Key.RIGHT_CTRL,  # WinMac
    # Key.RIGHT_CTRL: Key.LEFT_CTRL,  # WinMac
...
```
