### ISSUE TITLE
Error when installing in Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by flozano** [rbreaves/kinto#134]
```
update-initramfs: Generating /boot/initrd.img-5.4.0-26-generic
'./.xkb' -> '/home/flozano/.xkb/'
'./.xkb/symbols' -> '/home/flozano/.xkb/symbols'
'./.xkb/symbols/chromebook' -> '/home/flozano/.xkb/symbols/chromebook'
'./.xkb/symbols/mac_gui' -> '/home/flozano/.xkb/symbols/mac_gui'
'./.xkb/symbols/mac_term' -> '/home/flozano/.xkb/symbols/mac_term'
'./.xkb/symbols/mac_term_chromebook' -> '/home/flozano/.xkb/symbols/mac_term_chromebook'
'./.xkb/types' -> '/home/flozano/.xkb/types'
'./.xkb/types/mac_gui' -> '/home/flozano/.xkb/types/mac_gui'
'./.xkb/types/mac_term' -> '/home/flozano/.xkb/types/mac_term'

If Kinto is already running it will be stopped...
If you cancel the installer you can re-run Kinto via
 systemctl --user start keyswap
Failed to stop keyswap.service: Unit keyswap.service not loaded.
Traceback (most recent call last):
  File "./setup.py", line 442, in <module>
    setShortcuts()
  File "./setup.py", line 56, in setShortcuts
    print("\nDetected " + distro + " " + distroVersion.strip() + " DE: " + dename + "\n")
UnboundLocalError: local variable 'distro' referenced before assignment
```

then:
```
flozano@myhost:~/kinto$  systemctl --user start keyswap
Failed to start keyswap.service: Unit keyswap.service not found.

```

**Comment by rbreaves** [comment]
That is odd, I shouldn't have to define a global variable in a function when I am just referencing it in python. Oh well, updated it so it is explicitly declared. I have not yet installed a 20.04 VM, so you'll have to test it again and let me know, but I will set one up soon.

Master and dev have hotfixes now to fix the distro variable error. I just broke it last night while trying to add additional support for Fedora.

**Comment by flozano** [comment]
I confirmed now it installs cleanly. 

However the behaviour I see is not what I expected. I (naively?) expected the keyboard to be the same as on my Mac (copy/paste and such), but it's very different. I use a realforce win keyboard with my Mac and I expected copy/paste and other keys to work the same as there, but they aren't. It looks like the ALT and the Win key are switched? Or is it that maybe 20.04 is too new and all this setup is not tested yet there? I will probably test this in an older ubuntu env (as I'm just evaluating if it'd be OK for me to move to a linux desktop), and investigate further.

The installation error is gone, so I'm closing this. Thanks a lot.

**Comment by rbreaves** [comment]
No problem @flozano and it should mirror your mac keyboard pretty closely, so I think you understand it right lol.

What may have occurred is selecting the wrong keyboard type during the initial install? But I see in your log above that it appears you did select the Windows keyboard option.. that option should have mapped Alt to Ctrl, Win to Alt and Ctrl to Super/Win. If you are using a real Apple keyboard then the Alt and Cmd key do become swapped on the HID driver level before xkb further swaps it - this is so that if you change out an official mac keyboard with a windows based keyboard you won't have to reinstall Kinto. You could even have 2 keyboards attached and they will both work.

Not sure why 20.04 would change any of that, that would be a pretty big change to how xkb operates if it did.

Also you can switch to the dev branch (just say no to the experimental browser back/forward hotkeys). The xkeysnail implementation of Kinto is better than the xkb implementation in practically every way besides those 2 browser hotkeys.

**Comment by rbreaves** [comment]
@flozano you could also try the “Mac Only” setup option, but you may need to run the uninstall first. The Mac Only setup will not swap Alt & Cmd before it begins the actual key remap.

It’s really meant for MacBooks & VMs on MacBooks, but 3rd party Mac keyboards too.

**Comment by flozano** [comment]
Thanks, will try it today

**Comment by flozano** [comment]
I have installed latest, tried with xkeysnail and mac-only keyboard, and it behaves same as OS X in most cases. THANKS! this is really useful. I see CTRL+C still works as-is in terminal app, and I can copy/paste with cmd+C. 

I think there is a slight difference as opposed to using OS X with same keyboard and CMD+arrow/backspace vs ALT+arrow/backspace, but I'll try to narrow and document it properly before reporting.

Again, thanks for this project.
