### ISSUE TITLE
Embedded terminal in IntelliJ IDEA (xkeysnail, ubuntu 20.04)

### ISSUE THREAD

**Issue by Mahoney** [rbreaves/kinto#181]
Hi,

I'm hoping I can contribute some stuff back, but at the moment I'm very raw on understanding this stuff...

IntelliJ IDEA has an embedded terminal, which is quite useful because it opens in the root directory of the current project, and you can also open arbitrary project directories in it.

However, at present things that work in the "real" terminal don't work in the embedded one - noticeably ctrl-c for SIGINT, ctrl-a for start of line, ctrl-e for end of line, alt left/right arrow for move one word.

Is that even a solvable problem? The special casing of terminal apps seems to rely on their window handle, so it's hard to see how it would work when the terminal is only part of the application's functionality.

**Comment by Mahoney** [comment]
Related - I've created an IntelliJ keymap which basically takes their macOS one and swaps meta for ctrl wherever they occur. Does that sound like the right approach? It works, mostly.

**Comment by rbreaves** [comment]
> Related - I've created an IntelliJ keymap which basically takes their macOS one and swaps meta for ctrl wherever they occur. Does that sound like the right approach? It works, mostly.

I think I you got it right - considering the GUI layout for Kinto is actually this on the left side Super (Meta), Alt, Ctrl versus macs  Ctrl, Alt, Cmd (Meta). 

If you were to take the Ctrl key keymaps in your IDE and then create xkeysnail translations to go from Super (Meta) -> Ctrl then yes that would fix all of your keymaps for that particular app. And I would be happy to merge that changes into master.

**Comment by rbreaves** [comment]
@Mahoney I have now added IntelliJ remap support for Windows and Linux within the master branch of Kinto.

Come to find out detecting the terminal may not be needed because we can still remap the Super (physical Ctrl key as needed for the key terminal hotkeys, not as nice as switching to the terminal keymap but good enough imo). I will be closing this ticket but if you believe it needs more terminal functionality or anything else under IntelliJ then just let me know.

**Comment by Mahoney** [comment]
Fantastic, thanks!

Sorry, not had much time to follow up on any of this recently.
