### ISSUE TITLE
Does Kinto work with WSL 2?

### ISSUE THREAD

**Issue by tiagofassoni** [rbreaves/kinto#202]
First of all, thanks so much for this project! Appreciate it so much.

Microsoft has made a mess out of Windows Subsystem for Linux 1 and 2, and both of them have different features and different paradigms, so any ideas if it will work with 2?

Btw, going to install now on 2 and see how it goes.

**Comment by rbreaves** [comment]
My hope is that it already does but to be honest you may need to update the ./Windows/kinto.ahk file to support it. Just find where the existing Ubuntu.exe or WSL entry is & make sure to add wsl2 to it based on its app name.

I’ve not trust MS enough to become part of the insider program atm.

**Comment by tiagofassoni** [comment]
Lucky you, who doesn't trust. I needed to update my workstation to the
newest version of windows so it would work with WSL 2.

And now damn thing halts on boot. Yey!

Em sáb, 6 de jun de 2020 18:32, Ben Reaves <notifications@github.com>
escreveu:

**Comment by rbreaves** [comment]
Also, as of today, I’m working on a new update to the ahk Windows script. The registry key swap, log off & log on part of the initial setup will be going away soon.

I’ve figured out how to reliably swap modifiers w/o changing scan codes in the registry at all. Main issue w/ that has always been that you can’t change out windows & Mac based keyboard w/o reinstalling Kinto & signing off & back on.

Only reason it was done that way at all was because it greatly simplified the ahk script during a time I just wanted to get something out there. All I’m focused on now are refinements.

**Comment by tiagofassoni** [comment]
Thanks so much, Ben!

(although I won't be installing WSL 2 anytime soon, I'd rather have my
workstation, you know, working).
