### ISSUE TITLE
Limitedadmins sudoers syntax errors on antiX 19.2.1

### ISSUE THREAD

**Issue by RedBearAK** [rbreaves/kinto#224]
On a fresh install of antiX 19.2.1, an attempt to setup Kinto results in syntax error in /etc/sudoers.d/limitedadmins file, further resulting in a broken sudo system until the limitedadmins file is deleted. 

See attached output from running setup.py: 

[antix_error03.txt](https://github.com/rbreaves/kinto/files/4807620/antix_error03.txt)

This is kind of strange since MX is based on antiX and I didn't have these sudoers syntax errors on MX Linux 19.2. Only Gentoo on the Raspberry Pi 4 and antiX have so far disliked the limitedadmins file. 

This is a big problem since it breaks parts of the user's system (like shutting down from the GUI logout/shutdown menu) until the limitedadmins file is deleted, which can only be done by su-ing to root, which requires knowledge of how to su to root and how to find the file and delete it, and the knowledge that it would be safe to delete it. That's a lot of knowledge that new Linux users can't be expected to possess. I was only able to fix this problem because I had already become familiar with the location of the limitedadmins file and the knowledge that it is created by Kinto and would be safe to delete. I also knew from my previous attempts at manually editing limitedadmins that it was the cause of breaking sudo, and how to get out of it by su-ing to root. 

I was lucky. 

Seems like this requirement for running parts of Kinto via sudo needs a more widely compatible solution that is less liable to "break" the end user's system. At least a way to tentatively test for limitedadmins file compatibility with the system before proceeding with the rest of the Kinto setup. Visudo gives warnings about syntax errors before saving sudoers files. Maybe that could be part of the solution.

**Comment by rbreaves** [comment]
Do you have a suggestion on how to resolve the syntax errors across the board? If nothing else I need to either whitelist or blacklist distros till resolutions are found.

**Comment by RedBearAK** [comment]
Not yet, sorry to say. I've been trying to look through the sudoers man pages and such but so far I have no idea what could even be causing the syntax errors or why antiX would react so differently to something that works fine in MX Linux. 

The only ideas I've had so far is defining Cmnd_Alias entries and calling those instead of using the commands directly. But that would probably just be moving the syntax error to a different line. 

My only insight from the manual editing of limitedadmins previously was that the colon character had to be escaped to make it accept the xhost command.

**Comment by rbreaves** [comment]
Well I was hoping that by adding it as a separate file that it would be ignored in the event of any issue with the file - since it is not part of the actual sudoers file. Even if a universal way of formatting the file is not found it may be possible to run a command to verify that the file works on the distro before adding it.

Could be an issue where some sort of related dependency or binary to how sudoer works varies by its version, but if MX is based on antix then yea you would not expect that to be an issue.

Well I may be taking a break from updating this project for the next week or 2, but I will be monitoring the issue tickets and resolving anything I deem major and the way this breaks is pretty bad - but it is also outside of the supported distros listed. If you or anyone finds a clear resolutions or submits a PR to me then I will certainly take a look at it and merge it.

It's also been awhile since I have re-reviewed my roadmap in full but the only 2 things that are high priorities for me is getting 4-5 system trays built for the most popular DE's out there and after that adding a slew of shortcut keys for some of the most popular cross platform apps that I can think of, assuming they have any shortcut key differences to reconcile, some of them may not.

Also once the system trays are built I will be circling back to what works needs to be done on refining the installer. Some work has already been done on that front, but the addition of autodetect in the system tray for Windows makes me want to revisit it again for both installers (Linux & Windows), at the very least detect official Apple keyboards while allowing for an override on 3rd party Mac keyboards.

To me that is the only thing holding back the creation of the PPA and potentially getting it included with some distros. It needs to have a GUI &/or system tray that allows for the changing of some basic settings & its suspension or removal.

**Comment by RedBearAK** [comment]
Well, it is a separate file but it's "included" in the main sudoers file like an imported header file in a program. So it's like importing a broken header or other source file into your program when you try to compile it. The whole sudo system just barfs whenever the slightest thing is wrong, which is why they recommend using visudo to even do simple edits. So verifying that limitedadmins will work (and not break things) prior to putting it in place is going to be essential. 

At the moment it would appear to be a good idea to blacklist at least antiX and Gentoo or at least provide a severe warning and some easy-to-follow instructions on how to unb0rk the system if it causes a problem. Until we have some idea of a more generic way to identify the distros that will have this issue, it will just have to be blacklisted by distro name, I guess. 

At least Kinto is working on the most common distros so far without major issues. Things can only get better from here. 

The rest of that sounds great. More GUI interaction with Kinto would be neat. But even in its current state Kinto has already significantly enhanced my ability to be comfortable using Linux for more than a few painful minutes at a time. So thanks for that and enjoy your time away from the project. 

If I have any new discoveries or insights I will keep adding them to the pile. I'd really like to see Kinto included by default in many popular distros at some point.

**Comment by aaronjensen** [comment]
FWIW, I just hit this with Pop OS. I got out of it with `pkexec visudo -f /etc/sudoers.d/limitedadmins`.

**Comment by aaronjensen** [comment]
FWIW, I had this problem because I had `which` aliased to `type -a` and the installation scripts relied on this. The installation scripts should probably use `\which` instead of `which` to be safe.

**Comment by rbreaves** [comment]
> FWIW, I had this problem because I had `which` aliased to `type -a` and the installation scripts relied on this. The installation scripts should probably use `\which` instead of `which` to be safe.

Interesting, I wouldn’t have expected a user to alias which lol.

**Comment by aaronjensen** [comment]
Yeah, I should probably just use `type -a` if I want it... I cribbed it from someone long ago and got used to it.

**Comment by rbreaves** [comment]
Alias busting on which is now implemented and merged into master.

https://github.com/rbreaves/kinto/commit/86904366291b5b69cf9c0899d0f4d82046487660

**Comment by aaronjensen** [comment]
That's great, thank you.

**Comment by rbreaves** [comment]
Release v1.2 is out now, nothing specifically for AntiX was added but perhaps the updated xkeysnail_service.sh could make adding specific configurations needed for specific distros a bit easier. I will accept any solid info on how to resolve things for any distro or PR request.

Closing for now.
