### ISSUE TITLE
Install instructions unclear

### ISSUE THREAD

**Issue by KonstantinSchubert** [rbreaves/kinto#225]
Hi, I am trying to install kinto on my ubuntu linux desktop.

When I install, it first gives me these 3 options

```
1) Kinto - xkeysnail (udev/x11) - Recommended
2) Kinto - Original xkb/x11 implementation
3) Uninstall Kinto - xkeysnail
4) Uninstall Kinto - Original xkb
```
This is still relatively clear- I want to install and choose the recommended option -> 1)

However, the choice in the next step is unclear to me:

```
Install Kinto - xkeysnail (udev)
  1) Windows & Mac (HID driver)
  2) Mac Only & VMs on Macbooks
  3) Chromebook
```

Since I am on Linux, I would expect that I should choose a "Linux" option? But there is no such option. So I guess I must be mis-understanding something?

**Comment by rbreaves** [comment]
The options refer to the keyboard types, not the operating system. Sorry if that is not clear.

```
Install Kinto - xkeysnail (udev)
  1) Windows & Mac (HID driver) - Most Standard Keyboards & Official Apple Keyboards
  2) Mac Only & VMs on Macbooks - Mac keyboards or macbooks running macOS & Linux in VM which do not have the official HID driver running
  3) Chromebook - Chromebook style keyboards - potentially IBM Model M style keyboards or HHKB keyboards as well - but untested on those. Keyboards without a Win or Super key essentially.
```

I do plan to rewrite the installer in the coming weeks to auto-detect official Apple keyboards vs everything else, for the most part. 3rd party Apple keyboard can potentially be detected on both Windows and Linux via their Vendor and Product IDs, but it requires that they be identified in some way.

Apple is easy because they only make Apple based keyboards, but other Vendors that make a mix will need to be carefully selected to trigger and Mac based installed.

**Comment by rbreaves** [comment]
I've gone ahead and updated master with clearer descriptions as I don't think you are the first one to be confused by what the current installer is asking.
