### ISSUE TITLE
Add shortcuts to move between tabs left/right

### ISSUE THREAD

**Issue by bilby91** [rbreaves/kinto#250]
Hello!

Great project!! It was really easy to get the mac experience really easy :) 

I was wondering if it would be possible to override at the system level the shortcut to move between tabs ? In macOS I use `CMD + SHIFT + [` to move into the left tab and `CMD + SHIFT + ]` to move into the right tab. 

I'm currently using `pop!_os` and it seems that `FN + CTL + UP` (mac keyboard wise) moves to the left and `FN + CTL + DOWN` does it to the right.

Looking for any advice. 

Thanks!

**Comment by rbreaves** [comment]
Sublime Text 3 for Linux and Windows has this support added already, since I do not know which application(s) you need or want it added to you will have to discover its class name and create a new entry or you could add it to the none & terminal entries if you really to apply it to everything regardless.

Run this to discover the wm class name

    xprop -spy

https://github.com/rbreaves/kinto/blob/master/xkeysnail-config/kinto.py
```
# Keybindings for Sublime Text
define_keymap(re.compile("Sublime_text", re.IGNORECASE),{
...
    K("C-Shift-left_brace"): K("C-PAGE_DOWN"),  # next_view
    K("C-Shift-right_brace"): K("C-PAGE_UP"),   # prev_view
...
```

**Comment by rbreaves** [comment]
Closing ticket. Without knowing the name of the app I cannot add a fix for it.

**Comment by RedBearAK** [comment]
@bilby91 

PR #536 should take care of adding support for Cmd+Shift+Braces for tab navigation, at least for web browsers.

**Comment by RedBearAK** [comment]
@bilby91 

PR #541 should add support for Cmd+Shift+Braces for tab navigation in most Linux file managers.
