### ISSUE TITLE
Mac keyboard: two keys inverted

### ISSUE THREAD

**Issue by Pidgeey** [rbreaves/kinto#257]
Hi, 

I'm using kinto with a laptop with linux Pop_os and it work like a charm. 

But, when i want to use my official mac external keyboard, there is a problem with two keys, the beacon key (<>) and the at key (@#). They are inverted.  

how can i fix it ? 

(The problem is not present on the laptop keyboard.)

**Comment by rbreaves** [comment]
That can be adjusted in the key.py file under the xkeysnail directory but you’ll need to reinstall it after modifying it.

Not sure about how to create 2 different sets though.. xkeysnail functionality my need something added to support different keymaps per keyboard product I’d & vendor Id.

**Comment by rbreaves** [comment]
Will re-open if I hear back. I've not experienced this mismatching with my own official Apple keyboard, so it is difficult to test.

If a Product ID is provided then a specific fix may be possible, although changes to xkeysnail upstream may need to occur. I believe lsusb will list out the vendor and product id for you. I am also not aware of xkeysnail currently change their default keymap based on Product ID so that would likely be a new feature.
https://github.com/mooz/xkeysnail/issues

**Comment by argeas** [comment]
HI I just installed kinto on ubuntu and pared a first gen mac BT keyboard (A1314) and my alt is the CMD after installing kinto. 
Should this be the case ? 

Im running on ubuntu:

Kinto 1.2-4

NAME="Ubuntu"
VERSION="20.10 (Groovy Gorilla)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.10"
VERSION_ID="20.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy

uname -r
5.8.0-28-generic

**Comment by rbreaves** [comment]
It should not be... trying to think how that could happen.. I mean even if Kinto was already running while you ran another installer and the process wasn't ended by the Kinto installer before the Keyboard Assist a mac based keyboard would always have the 2nd key from the space bar as Alt initially..

Only way I can see that happening is if during the installer you were to press the Cmd key instead of the Alt key (2nd key from the spacebar) as the installer would then assume you are using a Windows keyboard if you were to hit Cmd during the Keyboard Assistant phase.

**Comment by rbreaves** [comment]
@argeas There is another possibility.. you might be an early user of Kinto - in which case I might have set your Apple keyboard driver to swap the Alt and Cmd key to align it closer to a Windows keyboard. I no longer do this as a default as it clearly creates some confusion, more than it worth dealing with. The installer is supposed to undo that - but perhaps it did not for some reason.

You should be able to run this command to unset it if needed.

```
cat /etc/modprobe.d/hid_apple.conf

echo "options hid_apple swap_opt_cmd=0" | sudo tee -a /etc/modprobe.d/hid_apple.conf
sudo update-initramfs -u -k all
```

I like swapping Alt & Cmd personally because I can plug in other Windows keyboards without needing to change anything with Kinto and so there's a "Windows & Apple*" keyboard option. It is not a default and the Keyboard Assistant will never set a user to that configuration if they don't change to it manually.

I also had early Kinto users.. or adopters that got rather angry at me for setting the Apple keyboard driver to swap those keys because I initially left out the proper command to uninstall that change and in other cases they never ran the uninstaller at all and tried removing it manually without complete success 😅. In either case I am trying to be less destructive whether they run my uninstaller or not.

**Comment by argeas** [comment]
Hi @rbreaves thanks for the reply. 

So I have installed it on a Lenovo L380... and I Installed Kinto on the native laptop keyboard.

I guess if I install Kinto while having already pluged in the Apple BT keyboard during setup it will probably get configured correctly?

**Comment by rbreaves** [comment]
If you ever installed a version pre 1.2 then I’d probably uninstall it & start fresh. After 1.2 though installing on top should be fine - you can always change your keyboard type after the install just fine via the app or task tray.

**Comment by argeas** [comment]
Ah ok thanks, 
No I used the latest version on a fresh ubuntu install. So I will try changing the keyboard type!

Thanks again!

**Comment by raraz15** [comment]
> That can be adjusted in the key.py file under the xkeysnail directory but you’ll need to reinstall it after modifying it.
> 
> Not sure about how to create 2 different sets though.. xkeysnail functionality may need something added to support different keymaps per keyboard product I’d & vendor Id.

I would like to do this between `~ (grave key) and §± (section key) but I can not find the name of the § character in `key.py`. Which number does it correspond to?

**Comment by RedBearAK** [comment]
@raraz15 

> I would like to do this between `~ (grave key) and §± (section key) but I can not find the name of the § character in key.py. Which number does it correspond to?

If you are talking about a key that is in the same physical location that the Grave key would usually be (left side above Tab and below Escape), then it probably has the same key code. Which then presents a bit of a problem if you try to mess with the `key.py` file, because "Grave" is used as a key name in the config file (for switching between the windows of a single app, depends on the desktop environment). 

The section symbol and the plus-minus symbol don't appear on the US layout. If they are level 3/4 characters (meaning you have to use a special key like Alt_Gr on the right side of the space bar to get to them) then you should look at the option in the Kinto tray icon menu that enables the use of Alt_Gr again. 

If you can't figure this out, open an issue on my related repo (I'm not the Kinto dev, just a contributor, and have a separate project that works almost the same way, where the keymapper has similar issues with international keyboards and characters). See link: 

https://github.com/RedBearAK/toshy/issues/
