### ISSUE TITLE
My CMD key doesn't open the activities view after uninstalling Kinto

### ISSUE THREAD

**Issue by AndrewVos** [rbreaves/kinto#261]
**Describe the bug**

My CMD key does not open the activities window. 

**Expected behavior**

After installing and uninstalling Kinto I expected my shortcuts to be reset.

**Install Type:** Bare Metal
**Distro:** Ubuntu 20.04
**DE:** Gnome
**Branch:** master
**Commit:** 558e86dd78107dd4f15d599427630de436a2b015

**Comment by rbreaves** [comment]
I apologize about that, I have completely redone how Kinto installs and uninstalls so that system level keys are not touched unless they are not set at all. If something is set then the command line will let you know and you can decide whether or not to remap it as I will also give you the command to handle it via the terminal.

Later I may add an additional GUI window that lets you decide how to proceed as well, especially as I prepare it for the repos at some point.
