### ISSUE TITLE
Pressing ctrl + space in Vscode Windows 10 does not trigger "trigger suggest"

### ISSUE THREAD

**Issue by timohermans** [rbreaves/kinto#264]
**Describe the bug**
ctrl + space does not execute 'trigger suggest' in vscode

**Expected behavior**
When pressing ctrl+space (physical buttons, not the mapped onces), vscode doesn't perform "trigger suggest".

**Install Type:** bare metal
**Distro:** Windows 10 1909
**Branch:** master

**Comment by timohermans** [comment]
I'm really really loving Kinto btw 👍 ! I just don't know how to fix this issue. If it's my oversight, I'm very sorry!

**Comment by rbreaves** [comment]
Thanks for letting me know and it's not a problem at all. You can look at the commit I created as well for an idea on how to go about adding similar shortcuts if you find anything missing in the future. I'll accept any PR's that come my way that further this project to achieve matching hotkeys.

```
; Sublime Text Remaps for VS Code
#IfWinActive ahk_group vscode
    #Space::Send ^{Space}                                ; Basic code completion
...

#IfWinActive ahk_exe sublime_text.exe
    #Space::Send ^{Space}                                   ; Basic code completion
...
```

Also I pretty much just went in and duplicated a hotkey that I had added to IntelliJ IDEA already that does the same remapping. I hadn't noticed that it was missing on sublime text 3 or vscode. Kinda surprised it got missed on ST3, but less surprised about VS Code. ST3 is still my primary for the most part and I probably need to go through VS Code with a more fine tooth comb.

At some point it might be better to even condense matching hotkeys btwn code editors into a single matching block for code editors in general, but for now I don't plan to do that - aka there will be repetitive hotkeys defined. I do a little bit of condensing of hotkeys with terminals, but mostly because I can't reasonably test all terminals as thoroughly as I would like, whether it be on Windows or Linux. I make a best effort attempts at remapping their keys for basic things like copy, paste, open/close tabs, etc, and then move on. I do try to be more thorough with code editors, but there's also only 3 that I am currently concerned with ST3, VSC, and IntelliJ and anyone can add additional support for others as well.

**Comment by timohermans** [comment]
Thanks for the very quick fix!

I just tried to test it. When I know ctrl + space within vscode, but it now opens the windows start menu 😅

**Comment by rbreaves** [comment]
Thank you for testing it, I apparently had only tested it while commenting out the Cmd+Spaces remap and did not realized I had not commented it back in. Sorry about that, I am about to do another commit that should fix this for real this time. The $ prevents another remap from loop into the Cmd+Space remap - which I want to open the start menu.

**Comment by timohermans** [comment]
I'll test it asap

**Comment by rbreaves** [comment]
Also the latest PR adds support for Windows 10 user profile names that have spaces in them.. I noticed that issue last week and finally got to sit down and fix it tonight.

**Comment by timohermans** [comment]
You are incredible! It works. Can I buy you a beer(donation) somewhere? 😁😁🎉

**Comment by rbreaves** [comment]
Thanks, I’m glad to hear that you’re enjoying it. I’ll try & get around to adding a donation button at some point.

**Comment by rbreaves** [comment]
I just submitted another PR/merge into master. I realized I may have introduced a bug that could cause the keyboard type to reset itself to a Windows style keyboard - even if you are using an Apple style/branded keyboard.

For some reason the usb check script started to fail once I started to add explicit user profile paths into various parts of the program. I am pretty sure it has now been fully updated and the script will no longer fail/reset to the Windows style keyboard (of course if you are already using a Windows style keyboard then I doubt you noticed this issue).

**Comment by timohermans** [comment]
Yeah I was using a windows keyboard all along, haha. 😊

I've used Kinto all night to dev on Windows 10 and I'm loving every second of it. 

The only thing that's stuck in my muscle memory is cycling through lists (cmd/alt + p to bring up the file list, then ctrl + n or ctrl + p to go to next/previous item). This doesn't work on vscode (it opens up a new vscode window xD). I wish my autohotkey skills were better, haha.

**Comment by rbreaves** [comment]
Odd, it doesn't create a new Window for me, but it does open the Windows Projector and screen settings options on my system. I have updated the hotkeys for vscode now so that when you press Cmd + P you can then use Ctrl + p/n to traverse the list as next and previous as you would expect.

I have merged what you mentioned into master.

**Autohotkey Legend**

\# = Super
! = Alt
^ = Ctrl
\+ = Shift

Physical/Relative locations
^ = 1st modifier closest to Spacebar
! = 2nd Closest modifier to Spacebar
\# = 3rd Closest modifier to Spacebar

```
#IfWinActive ahk_group vscode
    #p::send {Up}                                        ; Allow for traversing quick list
    #n::send {Down}                                      ; Allow for traversing quick list
...
```

**Comment by timohermans** [comment]
Ah, I created a separate ahk script to test something else. I also got the projection bar at first 🤦‍♂️.

And your solution is way more elegant! I tried to map cmd/alt + p/n to ctrl + p/n 😅, which didn't work

**Comment by rbreaves** [comment]
Yea, it can be hard at times to keep things straight when trying to do a remap - and depending where you are at in the ahk script it can change the modifier key you'd be referencing. Almost all remaps are done after the base level modifiers have been remapped, the sole exception is the alt+tab & ctrl+tab combos, I remap them before the remapping the base level modifiers otherwise things get to be messier. I am actually pretty impressed with how well autohotkey can handle it at all - it was a much bigger nightmare under Linux to get sorted out than on Windows largely thanks to ahk.

I am used to thinking about the relative or virtual key locations, after the initial remap, being what I am working with instead of the physical.

**Comment by timohermans** [comment]
Is there a preferred way for you to ask my questions btw 😊? 

If you sometimes need a tester on Windows, let me know if I can be of assistance!

Also, do you know any way to work around the UAC popup for autohotkey.exe that spawns every time you reboot the machine?

**Comment by timohermans** [comment]
Ah btw, when I boot my windows laptop Kinto always starts with mac keyboard. A little bit the reverse of what you were talking a bout 2 days ago

**Comment by rbreaves** [comment]
There probably is a way to avoid the UAC but it’d require some work.. setting up of a schedule task essentially & doesn’t seem like it’s worth the effort imo.

Also I don’t know why it’s default to a Mac keyboard on reboot :/.. wouldn’t think that’d be possible. Regardless major changes are happening in my ibmmmm & alpha branches that I imagine will resolve that.

The menu tray is better defined, autodetect keyboards can be toggled, chromebook & IBM keyboard support has been added. If you’d like to test it just checkout ibmmmm & reinstall.

Atm I’m updating it for Linux as it’s system tray was never finished & needs parity. The Windows System tray will likely gain 1 or 2 more options as well.

**Comment by rbreaves** [comment]
> You are incredible! It works. Can I buy you a beer(donation) somewhere? 😁😁🎉

I am not sure if it was you or someone else who donated to me via paypal awhile back lol. I am kinda horrible because I forgot to respond to them and thank them as I definitely appreciate it! And I'd definitely take an original New Castle or Guinness in a pub lol - short of that though I have now added this [Amazon Wishlist](https://www.amazon.com/hz/wishlist/ls/3EVXR21VFKD9Z?ref_=wl_share) for anyone that wants to donate to me &/or this Kinto project!

https://www.amazon.com/hz/wishlist/ls/3EVXR21VFKD9Z?ref_=wl_share

I hope you are continuing to enjoy Kinto and the latest updates!
