### ISSUE TITLE
Specifying the device

### ISSUE THREAD

**Issue by mauricekraus** [rbreaves/kinto#275]
Hello,

I have a Bluetooth device (Logitech MxKeys), unfortunately xkeysnail does not seem to be able to find it when viewing the xkeysnail logs. Since xkeysnail supports the --devices flag, my question is if this is also possible in kinto. At the moment nothing works for me.

**Comment by rbreaves** [comment]
I am not sure, if xkeysnail isn't picking up your keyboard then maybe make a post about it on the xkeysnail repo? If they fix it there then I can merge the changes into my fork of their project.

I don't mind trying to dig into it further myself if I had a Logitech MxKeys keyboard. I do have a couple of logitech keyboards, one bluetooth an another on a proprietary format that I could try later.

**Comment by mauricekraus** [comment]
Hmm I mean if I specify the device directly in xkeysnail (--devices /dev/input/event 3 "Logitech MxKeys") it got recognized, however this does not seem to be an option with Kinto. Btw I don't use Bluetooth (I accidentally thought so) I use the proprietary connector from Logitech (unifying connector) maybe this helps. If you have time to check it out ur self this would be really nice.
Additionally I use arch with i3wm maybe this is an error source as well.

**Comment by rbreaves** [comment]
@mauricekraus interesting, if nothing else I can provide an option to pass through the input ID to Kinto & this xkeysnail.. although w/ that ID I suspect can change so I might want to flesh it out to match the name & not the ID.

**Comment by rbreaves** [comment]
@mauricekraus I will need to circle back to this in the future now that v1.2 has been released, a custom device input option I suppose could be added to the fast keyboard switching menu.

**Comment by rbreaves** [comment]
I guess I should add that you can more easily edit the service file directly from the GUI app or system tray with Kinto v1.2, so adding that in ought to be relatively easy even without a more direct UI way of doing it.

I think I will consider this closed, because generally speaking xkeysnail's ability to pickup keyboards is pretty good and should probably be addressed upstream, at which point I'd include the fix with Kinto.

https://github.com/mooz/xkeysnail/issues
