### ISSUE TITLE
HELP, working well but i'd like to use key "FN" like superkey

### ISSUE THREAD

**Issue by webmobiles** [rbreaves/kinto#28]
this is the first time that i find something that works very well, the only pity, my new keyboard microsoft has the key "FN" in the place the superkey. I mean superkey is one place to the right, it's a way to use this package to use "FN" key instead suiperkey, I do mainly copy paste on gnome and terminal. thanks

**Comment by rbreaves** [comment]
Thanks, but sadly most fn keys occur on a hardware level. Your OS doesn’t see it.. but you can make sure by running xev or “ showkey -s” in your terminal & then just pressing fn & see if a keycode appears.. It’s doubtful though. :/

And sorry about that.. I’ve seen plenty of nice looking laptops get completely ignored by me due to poor fn placement (Lenovo though allows for a swap in bios at least).
