### ISSUE TITLE
Super key in linux terminals

### ISSUE THREAD

**Issue by benortiz** [rbreaves/kinto#287]
Thanks for such a wonderful tool! It really has made switching between multiple operating systems much more seamless.

I'm trying to understand how to use this tool in terminals and still get a super key. There's probably something obvious that I'm missing that I can do in terms of configuration to make this happen, but I'm not seeing it 😬 My specific reason for wanting this is I have some system-level shortcuts bound to ctrl+shift+super+alt, but I can't seem to trigger then when I'm in a terminal application.

Thanks for your assistance!

**Comment by rbreaves** [comment]
I actually do eliminate the Super key mostly during terminal usage, except for things like virtual desktop switching. There probably should be other exceptions but currently that is the main one.

I am not entirely sure how Kinto or xkeysnail would handle that combo because you would essentially be pressing Left Control + Alt + Right Control + Shift and I have not tested any combos during terminal usage with Left and Right Control personally.

https://github.com/rbreaves/kinto/blob/master/xkeysnail-config/kinto.py
Terminal command start at line 356
If I were to add something along the lines you suggest it would look like this
```
     K("LC-M-RC-Shift-??"): K("??"),
```

Note: to map to Alt it is M and to map to Super it is Super.

For all intents and purposes the super key doesn't actually exist during terminal usage because it would complicate the keymap significantly more than having the defaults as they exist now. On the left side of the equation you can easily translate it back to the Super key and whatever combo you need it as for the program/terminal or OS.

Let me know if the above works for you or not.

**Comment by rbreaves** [comment]
Sorry if my response was longer than you would have liked - I am just not sure which way you would prefer to go about fixing the issue as there are legitimately 3 different ways that I could see handling it and it all depends on how important and how many Super key combos you are concerned with. My main concerns with the terminal surrounded only the Control and Alt keys.. for whatever reason I never or rarely deal with the Super key during terminal usage so it was very easy to ignore it for the most part.

**Comment by benortiz** [comment]
@rbreaves your response was great! It just took me a while to get around to trying them out. I was also quite surprised so I was confident I was missing something obvious, and I was!

I ended up going with the first approach you laid out, like this:

```
K("LC-M-RC-Shift-c"): K("RC-Shift-M-Super-c")
```

When I was trying something like this before, I had the Super shortcut on the right instead of the left and I wasn't looking for RC and LC. One note, I had to use `RC` instead of `C` on the right because otherwise I'd get a cryptic error `KeyError: <Modifier.CONTROL: 2>`. For a while I thought it was upset that I had LC/RC on the left, but on a lark I decided to try specifying which ctrl on the right and it worked! 🎉 

For my use case, I only have a handful of these that target opening or switching to specific applications, so it's not a big deal for me to add a line for each shortcut. Everything else has been so seamless in the terminal I'd be afraid to make any more foundational changes!

Thanks so much again for laying out so many options and helping me get this working! Hopefully others will find these options useful as well :)
