### ISSUE TITLE
Support for Firefox/Chrome Back/Forward hotkeys (Cmd+Left/Right) disabled on master w/ xkeysnail?

### ISSUE THREAD

**Issue by eperitus** [rbreaves/kinto#291]
When I setup kinto on my Ubuntu Linux laptop, almost all the hotkeys work great (just like the Mac) except for those in Chrome/Brave, specifically alt-left/right for back/forward.  Instead, these keys go to the top/bottom of the page.

During setup, I noticed this message: `Support for Firefox/Chrome Back/Forward hotkeys (Cmd+Left/Right) disabled on master w/ xkeysnail?`

How can I enable support for these back/forward hotkeys?

**Comment by rbreaves** [comment]
Unfortunately I have been unable to work out an adequate solution for this involving xkeysnail to date. Whatever the fix ends up being will require some overhauling of the xkeysnail code itself. I have my own fork of xkeysnail that I work on, but I haven't in awhile due to more pressing matters with Kinto in general. (System tray and GUI app related)

I believe it is mentioned in my roadmap #32 , if not I will add it, but there is no ETA on when this feature will return due to the difficulty of registering the cursor status with xkeysnail - something I managed to pull off with my custom C written version of Kinto. It should be possible to bring back but stepping through the python code that makes up xkeysnail will be required.

I will be closing this issue ticket as it's a known issue with no ETA at this time.

**Comment by rbreaves** [comment]
A work around that you could do would involve opening up the ~/.config/kinto/kinto.py file and updating it so that those browsers no longer have the full word wise functionality built in and instead use back and forward on that combination.

Another thing I could do while working this out is add either of those configurations as an option in my new Tweaks menu coming out soon. It would be possible to at least give the users the choice of either configuration and perhaps back and forward buttons would be used more often in the browser than wordwise.

**Comment by eperitus** [comment]
Thanks for the quick reply, Ben.  That Tweaks menu option sounds great.  

I tried opening the file you mentioned but I'm not sure exactly what to change.  (Also don't know what word wise is, but I'm pretty sure I'd rather have the browser back/forward functionality.)

**Comment by rbreaves** [comment]
@eperitus I think I am agreeing with you, that in general people will likely use the back/forward hotkeys more often than wordwise (the ability to manipulate the location of the caret input for text via the same hotkey). I think I will make this change around the time I release the tweaks menu. The default will be to prioritize the back/forward buttons in browsers until I can implement a full fix for it co-exist with wordwise.

**Comment by wdfinch** [comment]
@eperitus one way to use your forward/back shortcut keys is to get an extension for your browser that allows custom shortcut mapping. I was able to use forward/back in Chrome via this method until this can be patched.

**Comment by eperitus** [comment]
@wdfinch thanks - do you have a suggestion on a safe extension that would work in Chrome/Brave for this on Linux?

**Comment by rbreaves** [comment]
I don’t but I think you can lift the word wise entries under the None section & add it to the browser section easily enough & just connect it to the proper back & forward hotkeys.. then restart the service.

**Comment by wdfinch** [comment]
Yes. I'm using this one on Chrome with Ubuntu and it works great. Unfortunately, it's not free. The other one I found that seemed decent was only available for windows. I'm not sure if it will work in Brave. Chrome does allow you to cancel your purchase within a short time, so you could test it out first before deciding if you want to keep using it. 

https://chrome.google.com/webstore/detail/shortkeys-custom-keyboard/logpjaacgmcbpdkdchjiaagddngobkck

**Comment by eperitus** [comment]
> I don’t but I think you can lift the word wise entries under the None section & add it to the browser section easily enough & just connect it to the proper back & forward hotkeys.. then restart the service.

Tried that but I’m not sure I’m editing the right file, tried editing kinto/xkeysnail/kinto.py.  Moved wordwise entries to browser section and uncommented browser keys.  Restarted xkeysnail and also tried rerunning setup, to no effect.

**Comment by rbreaves** [comment]
File location should be ~/.config/kinto/kinto.py. All files except a few are located there.

The ones that aren’t are for sudoers.d to have limitedadmins file for running kinto & autostart & shortcut menu icons/app.
