### ISSUE TITLE
Ctrl key does nothing in VSCode

### ISSUE THREAD

**Issue by phaberest** [rbreaves/kinto#305]
**Describe the bug**
I have keyboard shortcuts mapped to <kbd>Ctrl</kbd>+<kbd>Cmd</kbd>+`put random key here`, but they are seen as <kbd>Ctrl</kbd>+`random key here`

**Expected behavior**
I suppose the real <kbd>Ctrl</kbd> might be noped in kinto's configuration, but it might be useful to attach it to some less used key to be able to still perform keyboard combinations with it

**Install Type:** Bare Metal
**Distro:** Regolith 1.4.1
**DE:** Gnome + i3wm
**Branch:** master
**Commit:** 1aa23c2

**Comment by rbreaves** [comment]
Generally speaking Cmd is Ctrl as my ReadMe lays out & Super gets treated the physical Ctrl key as is also mention.. so GUI app wise Cmd+Ctrl remaps should be fine because they’ve sorta swapped places..

Whatever it is you’re doing ai think defaults need to be used in the app & then you can translate it in Kinto via xkeysnail or ahk if needed.

**Comment by phaberest** [comment]
I found out that I was missing the "ST3 hotkeys for VS Code" checkbox in the Kinto tweaks preferences, after that it works!

**Comment by rbreaves** [comment]
I will likely redo this to work w/ an official st3 key remap extension in vscode as well in a future update fyi.

There are still some behaviors it might not cover till I make that update.
