### ISSUE TITLE
cannot start on ubuntu 20.04

### ISSUE THREAD

**Issue by caitsithx** [rbreaves/kinto#311]
After launch kinto-gui.sh, xkeysnail service can not be started with following error. But if starting in debug mode, it's fine.
Nov 11 11:38:26 xili-ubuntu1804 sudo[38623]: localuser:root being added to access control list
Nov 11 11:38:26 xili-ubuntu1804 sudo[38622]: /bin/bash: --quiet: command not found
Nov 11 11:38:26 xili-ubuntu1804 systemd[1]: xkeysnail.service: Main process exited, code=exited, status=127/n/a
Nov 11 11:38:26 xili-ubuntu1804 systemd[1]: xkeysnail.service: Failed with result 'exit-code'.
Nov 11 11:38:29 xili-ubuntu1804 systemd[1]: xkeysnail.service: Scheduled restart job, restart counter is at 619.
Nov 11 11:38:29 xili-ubuntu1804 systemd[1]: Stopped xkeysnail.
Nov 11 11:38:29 xili-ubuntu1804 systemd[1]: Started xkeysnail.

**Comment by rbreaves** [comment]
Odd, you are the 2nd person that has posted something similar. It appears like it installing without setting the xkeysnail path in the xkeysnail.service file. That should not be occurring, but for some reason it is under some unknown circumstance.

**Comment by rbreaves** [comment]
Line 403 is supposed to set it properly.. although I am noticing I did not include '\\' in front of which for the xkeysnail entries which means if you have an alias set for which it could break what it is supposed to do during the setup process.

https://github.com/rbreaves/kinto/blob/master/xkeysnail_service.sh

https://github.com/rbreaves/kinto/blob/master/xkeysnail-config/xkeysnail.service

**Comment by collymore** [comment]
I've just had this same issue in Ubuntu 20.4,  I was able to run the kinto after removing the {} from around xkeysnail inside xkeysnail-config/xkeysnail.service

So it now reads as below and this allows it to install and run 
ExecStart=/usr/bin/sudo /bin/bash -c '/usr/bin/xhost +SI:localuser:root && {homedir}/.config/kinto/killdups.sh && xkeysnail --quiet --watch {homedir}/.config/kinto/kinto.py'

**Comment by caitsithx** [comment]
Thank you very much for the quick fix!

**Comment by ssaidnabiev** [comment]
Hi,
I have encountered the same problem.
I just want to know where is the file and what should I edit in order to avoid this problem. It just really annoys me. I can't boot the system on the first try. Every time it takes from 3 to 10 minutes before I switch off my computer hoping that it will boot next time.
Pressing Escape button show the boot log and it goes like this

[ok] Started xkeysnail.service
[ok] Started xkeysnail.service
[ok] Started xkeysnail.service
[ok] Started xkeysnail.service
[ok] Started xkeysnail.service
[ok] Started xkeysnail.service
....
....
....
.... indefinitely

Please help!
