### ISSUE TITLE
Existing AutoHotKey needs remapping after kinto.sh installed

### ISSUE THREAD

**Issue by sungeunbae** [rbreaves/kinto#331]
I had an existing AutoHotKey configuration to switch between English and Korean keyboard, and it stopped working. 

Let me start with a big of background.
A laptop bought in Korea has a dedicated key next to Right Alt, which is used to switch between English and Korean.  AutoHotKey sees this key as  `{vk15sc138}` . But on a keyboard that doesn't have the key, one can press Right Alt and Windows auto-detects it as the Eng<->Kor key. 

On a MacBook, it is done with Ctrl+Space. 

Previously this simple AutoHotKey setup allowed me to mimic the Macbook's behaviour.

```
^Space:: 
send, {vk15sc138} 
return
```

After Kinto.sh is installed, however, this stopped working.  It appears that my press of left control + space is no longer seen as `^Space`, but I struggle to figure out what I should replace it with.

Any suggestions will be greatly appreciated. Thank you.

**Comment by rbreaves** [comment]
As the readme states base level modifiers are remapped first - so ^Space is physical keys Cmd/Alt+Space.

You’re probably wanting Super because it’s on Control during GUI app usage, although ^Space works during terminal usage. Might want to read through my script though to apply Left Control only.. not sure.

Also ought to be relatively easy to just combine your script w/ mine. Closing ticket, let me know if you keep having issues.

**Comment by sungeunbae** [comment]
Thanks - Gave a go with `#Space`  and it worked. Perfect! Thanks so much
