### ISSUE TITLE
Is that possible to swap capslock and control?

### ISSUE THREAD

**Issue by Maggiking** [rbreaves/kinto#338]
First, thanks a lot for the software you put together. It really solves a lot of my problems.
But another thing, I was trying to change the Capslock and control key after the remapping by kinto. 
I can't find any easy way to do this. I guess due to the remapping; if I change Capslock and control, it will become cmd.

very appreciated if you can give me some idea about this.

**Comment by rbreaves** [comment]
Well technically Cmd is Ctrl - for me Cmd is just shorthand for primary modifier.

If you are on the Linux side then the Capslock to Cmd option in the tweaks menu should do it.

Should be easy to swap in the Kinto.ahk file under windows, but I don’t have a GUI menu option to do it atm.

**Comment by Maggiking** [comment]
Thanks. But is there any way I can make the Capslock as the ^ key in the mac? The one that is used for terminal commands.

**Comment by rbreaves** [comment]
Not entirely clear to me if we’re discussing linux but if so then look at line 24 when editing the config.

You can specify Left Ctrl instead of right if you want or add in 2 blocks of similar looking code with conditionals if you want to replicate the GUI vs Term stuff that happens. I think just reviewing the code, reading the readme or reading up on xkeysnail ought to be enough.

https://github.com/rbreaves/kinto/blob/master/xkeysnail-config/kinto.py

**Comment by rbreaves** [comment]
That does bring up an interesting point.. I should also include a capslock to Ctrl (LCtrl) & not just Cmd (RCtrl)... :/

**Comment by Maggiking** [comment]
Yes, I'm using linux. I modified the config file but in my case map caps to LCtrl and RCtrl does the same thing for some reason. But map it to Left Meta does what I want. Thanks a lot!
