### ISSUE TITLE
Ctrl-V behaviour in Vim

### ISSUE THREAD

**Issue by ukutaht** [rbreaves/kinto#346]
Hi, I'm a happy user of kinto, thanks for building it.

One thing I'm still missing is the standard behaviour of Ctrl-V in Vim. It is supposed to enter block visual mode as per the documentation: http://vimdoc.sourceforge.net/htmldoc/visual.html#CTRL-V

It seems that kinto intercepts that shortcut and pastes text before Vim can see and handle the key combination. Is there a way for me to disable left ctrl mappings so that vim can see the key combination? I tried playing around with `kinto.py` but I didn't manage to fix the issue.

I don't use `ctrl+c` `ctrl+v` for copy pasting anyways since that's not supported on mac. For copy-paste I use `cmd+c` and `cmd+v`

**Comment by rbreaves** [comment]
Which terminal app are you using? This may be unexpected or unintended behavior as the physical Ctrl-V should work as normal in all Terminals.

I can confirm this is the case for Microsoft’s Windows Terminal on Windows (commenting out Ctrl-c/v in Json config) but should be applicable to all.

**Comment by ukutaht** [comment]
I'm using the standard 'Terminal' app on Elementary OS

**Comment by rbreaves** [comment]
Thank you, I will re-review the kinto.py config file and make the appropriate changes later today I imagine, it will likely be a pretty easy fix, 1-3 lines.

**Comment by rbreaves** [comment]
I discovered what your problem is and there are a few ways to fix that, and I suppose I should add this to my installer for elementaryOS installs as their implementation of natural copy & paste really sucks..

You can either disable it in the GUI or via the terminal.

![image](https://user-images.githubusercontent.com/10969616/101440976-a27d9880-38dd-11eb-8924-46141b39e9e5.png)

elementaryOS 5.x
```
gsettings set io.elementary.terminal.settings natural-copy-paste false
```

elementaryOS 4.x
```
gsettings set org.pantheon.terminal.settings natural-copy-paste false
```
https://elementaryos.stackexchange.com/questions/2059/how-can-i-disable-natural-copy-paste-in-terminal

**Comment by ukutaht** [comment]
Thanks! Sorry I probably should have found it myself, nothing to do with Kinto :+1:
