### ISSUE TITLE
Unable to tile Terminal windows

### ISSUE THREAD

**Issue by dettmar** [rbreaves/kinto#391]
**Describe the bug**
After installing kinto, I'm not able to use the `Ctrl+Left`, `Ctrl+Right`, etc, in order to [tile the windows](https://help.ubuntu.com/stable/ubuntu-help/shell-windows-tiled.html.en) of Terminal, like in other programs.

**Expected behavior**
Tiling, using the `Ctrl+<direction>` buttons should work as in other programs.

**Install Type:** Bare Metal
**Distro:** Ubuntu 20.04.2
**DE:** Gnome
**Branch:** master
**Commit:** 50d53ba77f52d1f9a160d3135cfdc0f5910eb2c1

**Comment by rbreaves** [comment]
Ctrl-Arrow keys directly collides w/ wordwise, cursor text manipulations within apps. Pick a different hotkey combo as this isn’t going to change. Although Left Control - Arrow keys (physical Ctrl- Arrow keys that is) can be remapped however you want.

cmd-arrow key however isn’t changing. Closing ticket.

**Comment by dettmar** [comment]
Thanks for the quick response. I tried out other combinations like `Ctrl+Alt+<arrow>`,  `Alt+Cmd+<arrow>` and `Ctrl+Alt+Cmd+<arrow>`, but all seem to be blocked by the defaults of Terminal. Do you have a suggestion for a combination that could work?

**Comment by rbreaves** [comment]
It's not that you can't use Ctrl-Left/Right - you just can't use them directly, you will need to use Kinto to remap to them, otherwise it will be transformed to the proper wordwise/cursor manipulation stuff.

These are two alternatives and not you need to define them in the "None" (normal GUI remaps) and the terminal area to cover both and they look slightly differently but as far as the physical keys go they are exactly the same to the actual user perspective due to the dynamic modifier remapping going on.

```
...
define_keymap(None,{
...
K("C-Super-Left"): K("C-Left"),
# or
K("Super-M-Left"): K("C-Left"),
...
}
...
define_keymap(re.compile(termStr, re.IGNORECASE),{
...
K("LC-RC-Left"): K("C-Left"),
# or
K("LC-M-Left"): K("C-Left"),
...
}
...
```
