### ISSUE TITLE
Windows shortcuts no longer work? 

### ISSUE THREAD

**Issue by andyd0** [rbreaves/kinto#405]
I believe instead of using the Windows button for Windows shortcuts I would use Ctrl instead. At some point, that stopped working.  Is there something I need to change?

**Comment by rbreaves** [comment]
That should still be working as you would expect, the physical Ctrl key ought to be the Windows key in most cases, besides things like Ctrl+Tab or Ctrl+C in the terminal.

I also just made an update on master that helps expand this more so on Chromebooks than what it was doing previously. Chromebooks are limited though so I ended up converting the Right Alt key to a Win  key - but also the Capslock key if they are not on the official ChromeOS.

**Comment by andyd0** [comment]
So the shortcut I typically use is Win-E for opening windows explorer. With kinto Windows keyboard enabled, I can no longer open windows explorer using Ctrl-E. I used to be able to though.

**Comment by rbreaves** [comment]
That is intentional, macOS hotkeys > Windows hotkeys/Linux hotkeys. I have now added Alt-Cmd-Space as a replacement for Ctrl-E (aka Win-E) due to your post.

Ctrl-E is part of emacs style text cursor manipulation, a staple of *nix OS's and POSIX based systems.

Please consult your ~\.kinto\kinto.ahk file in the future for " #*:: " hotkeys or any hotkey you believe you are lacking and I will add their macOS counterparts, if they have no already been added. Otherwise - if there is a conflict then the Windows or Linux combo will not work out, but I do not disable hotkeys that do not conflict with known hotkeys which this project is geared towards. You may also use the appropriate thread going forward for any missing hotkeys. #115

# = Win
! = Alt
^ = Ctrl

I do need to update this thread as well but some hotkeys can be readibly seen in these translation tables #44 .

https://github.com/rbreaves/kinto/blob/master/windows/kinto.ahk

```
     #IfWinNotActive ahk_group terminals
        ; emacs style
        #n::Send {Down}
        #p::Send {Up}
        #f::Send {Right}
        #b::Send {Left}
        #a::Send {Home}
        #e::Send {End}
        #d::Send {Delete}
        #k::Send +{End}{Backspace}
    #If
    ```

**Comment by rbreaves** [comment]
Win+A - Notification = No replacement
Win+D - Show Desktop = Cmd+F3
