### ISSUE TITLE
Which file manager for OS X column view ('Miller columns')? 

### ISSUE THREAD

**Issue by bjohas** [rbreaves/kinto#427]
@RedBearAK - this a spin-off from https://github.com/rbreaves/kinto/issues/408

The thread mentions Caja, Dolphin, Nautilus, Nemo, PCManFM, SpaceFM, Thunar. I am using https://wiki.gnome.org/action/show/Apps/Files (standard with Ubuntu) but have also tried Pantheon (from elementary-os). 

Pantheon has got an  OS-X-Finder-type column view ('Miller columns'), but unfortunately doesn't seem to have many (or any?) configuration options.

Would it be possible to get the https://github.com/rbreaves/kinto/issues/408 -type keyboard shortcuts also done for Pantheon?

Or is there a different file manager for Linux with Miller columns?

(I'm on Ubuntu.)

**Comment by RedBearAK** [comment]
@bjohas 

Whether any Linux file manager implements a "Miller column" view like the Finder is outside the scope of Kinto.sh and my Finder mods, which just map common Finder-like keyboard shortcuts onto the corresponding standard shortcuts in each file manager. 

I've never really liked the column view in Finder as much as I like the sortable list view where the folders become expandable in the same view in a tree-like structure. That's the one I find most logical, least visually confusing, and easy to get around in. So I can't advise exactly which Linux file browsers actually have a Miller column view. But most I have seen don't appear to have that view mode. 

Most of them only have 3 view modes, some only have two. The standard view modes are: icon view, list (or "detailed") view (with sortable headers), and compact view. And the keyboard shortcuts vary but usually it's just Ctrl+(1,2,3) to switch between the views. I haven't tried to standardize those because I don't use them that much. I usually just pick list view and never change. 

As far as adding mappings for Pantheon, I'll need to fire up an install of elementary OS and see if the default file manager actually calls itself "pantheon" in its WM_CLASS attribute. Running `xprop -spy | grep -v grep | grep -i wm_class` in a terminal and then clicking the file manager window with the crosshair cursor should reveal that. 

I won't be surprised to find that the eOS file manager is probably just another fork of Nautilus, which is the "Files" app that you linked to. That's already supported in my Finder mod code blocks as "org.gnome.Nautilus". If I can get eOS installed somewhere I can make sure it works with the Finder mods. If you're already trying the Finder mod code blocks you can try to just add "pantheon" into the list of names in this line: 

```
define_keymap(re.compile("caja|dolphin|nemo|org.gnome.Nautilus|pcmanfm|spacefm|thunar", re.IGNORECASE),{
```

Like so: 

```
define_keymap(re.compile("caja|dolphin|nemo|org.gnome.Nautilus|pantheon|pcmanfm|spacefm|thunar", re.IGNORECASE),{
```

**Comment by RedBearAK** [comment]
@bjohas 

Well, I had to use a live ISO environment and it was much more difficult than it should have been, but I think I added full support for eOS "Files" to the best of my ability. 

Posted updated code for the entire file manager section in issue #408 thread. 

https://github.com/rbreaves/kinto/issues/408#issuecomment-799883406

If you're up to it you can make a backup of your `kinto.py` config file and paste the new code block in and restart Kinto.sh. I don't know if you're already trying to use this custom code, it's not part of Kinto.sh proper yet. 

BE WARNED: The pasted code block in the other thread has the "Enter key to rename" still enabled. So if you don't comment that line out, when you're renaming a file or the cursor is inside any kind of text field you will need to use the "Alternate Enter key" shortcut Ctrl+Shift+Enter to escape or "activate" the field. Unless you want to just use the mouse and click outside the text field, that works too when renaming, but not when attempting to do a [F]ind or "Go to [L]ocation" action. Sometimes there is an arrow or "Go" button you can click with the mouse, but if not you must use Ctrl+Shift+Enter to "Go". This is the major drawback for the moment with "Enter key to rename". 

If you don't want "Enter key to rename" just comment out these two lines (or just the first one, really): 

```
    K("Enter"): K("F2"),				    # Rename with Enter key
    K("RC-Shift-Enter"): K("Enter"),	    # Remap alternative "Enter" key to easily activate/exit text fields
```

> Pantheon has got an OS-X-Finder-type column view ('Miller columns'), but unfortunately doesn't seem to have many (or any?) configuration options.

You're right about there being no preferences accessible in eOS Files. That is one of the things that ultimately drove me away from eOS, the developers have gone down a road of excessively limiting user options. They want you to do things their way, period. I can't stand single-click to activate in my file managers, but there is no easy way to disable it in eOS. There used to be some Elementary Tweaks applications but they are defunct. GNOME Tweaks can help with fixing some things in eOS. I loved the UI but in the end there were just too many things I wanted to "fix".

**Comment by RedBearAK** [comment]
@rbreaves 

Maybe this issue can be closed now since Pantheon Files is supported in the Finder mods and the Finder mods were merged.

**Comment by rbreaves** [comment]
Sounds good to me, now closing.
