### ISSUE TITLE
Permission denied, unit not found on Fedora 34 Beta

### ISSUE THREAD

**Issue by RedBearAK** [rbreaves/kinto#438]
Testing my installer branch on Fedora 34 Beta (live boot environment): Works, but...

Setup goes fine and the GUI appears, but the `xkeysnail` service gets stuck in a fail-retry loop with a "permission denied" error related to `/usr/bin/sudo`. Also, for some reason `systemctl` refuses to see the service file when it's in `/usr/lib/systemd/system`, giving a "unit not found" error. It gets detected after being copied to `/etc/systemd/system`, but still won't initiate properly. 

The only way to start the `xkeysnail` service at the moment is to copy-paste and run the contents of the `ExecStart` command manually in a terminal. That produces no "permission denied" error and keyboard mapping starts working. 

Testing in a Fedora live image requires making a new user so you can change to X11 at the login screen.

**Comment by rbreaves** [comment]
Most likely an SELinux issue is it not? ReadMe & past issues bring it up. The installer is supposed to try & fix that though, requires log off & on, maybe a reboot.

**Comment by RedBearAK** [comment]
@rbreaves 

I did see some stuff about SELinux during setup and answered "y" to make it... permissive? I think that's what it said. But apparently it needs to be tweaked a bit? 

Reboot might be difficult since I was testing in a live environment. I'm interested in the pretty major UI changes coming with GNOME 40 so I'll probably take another look at Fedora 34 another time. I'll try to get more familiar with the SELinux issues. 

But mostly I was just trying to make sure the installer part works, and it still does. At least as far as installing the right packages and getting through the GUI setup dialog.

**Comment by RedBearAK** [comment]
@rbreaves 

OK, so I tried installing in a GNOME Box this time, disabled remapping in `kinto.py` on the host, and discovered a couple of central problems with the attempted automation of the SELinux fix for Fedora. 

One problem is that the `if` statement to actually apply the `sed` command to update the config file was not being triggered at all, because it was testing for "yn = yes" but "yn" would normally be just "y" because the prompt asked for "(y/n)". I'm switching it to testing for "setSE = yes" since that's the variable that gets set to "yes" inside the `case-esac` statement when you enter [Yy]. 

The second main issue is that the `sed` command would actually fail since it wasn't using `sudo`. But the script was not testing to see if the edit succeeded. So even if you typed in "yes" at the prompt instead of just "y", the edit wouldn't work, but the script would continue as if it was successful. 

I think I have just enough shell scripting ability to hammer this into a much more robust and reliable mechanism by the end of the day. 

Changing it from "enforcing" to "permissive" and rebooting does seem to completely resolve the "unit not found" and "permission denied" issues. Thanks for the pointer to the cause.

**Comment by RedBearAK** [comment]
@rbreaves 

Fix now in PR #437 

Tested working on a fresh Fedora 34 install in a GNOME Box. Should deal with every scenario except user applying the fix and then forgetting to reboot before running setup again. If I knew of a simple way to test whether SELinux was actually in permissive mode instead of enforcing mode, I'd put that in there too. Maybe I'll look into it. The installer should really kick the user out until they get into permissive mode successfully. 

But if SELinux mode is "enforcing", the edit should be applied reliably, and should always work now that it's using `sudo`, and if the edit for some reason fails it prompts the user to manually fix the file and reboot. In either case, it exits and tells the user to reboot before continuing with setup. 

The test for success checks whether there is a line "SELINUX=permissive" but also checks that there is NOT a line "SELINUX=enforcing" in `/etc/selinux/config`. A bit redundant but will prompt the user to manually check the file if the test fails in either direction. Wouldn't want to allow something like this to slide by: 

```
SELINUX=permissive
SELINUX=enforcing
```

**Comment by RedBearAK** [comment]
@rbreaves 

Added a check for the system actually being in Permissive mode (using output from `getenforce`). 

Seems to work well. It will keep kicking the user out of the installer as long as the system fails to report as "Permissive". Or in other words, until they reboot.

**Comment by RedBearAK** [comment]
@rbreaves 

Works fine on Fedora 34 Beta KDE spin too, but the vte library package name turns out to be "vte291" on the KDE version. I'll be adding that to the installer.

**Comment by prosac** [comment]
Hello,

while I am on Fedroa 33 still I have the same problem. I would like to point out that setting SELinux simply to permissive might not be such a good idea. Basically by that you disable the layer of security prevents applications to just do whatever they like to all files you as the user starting them have permissions on. In permissive mode violations of the policies would only be logged. See https://selinuxproject.org/page/Guide/Mode.

It has been years since I read a book about SELinux and do not have the _right_ fix in my head just now, but I will read a bit and come back here.

**Comment by prosac** [comment]
When xkeysnail.service lands in /usr/lib/systemd/system it has the SELinux context `unconfined_u:object_r:user_home_t:s0`. The systemd unit files that are placed there by the system have a different context:

```
cd /usr/lib/systemd/system
ls -Z
[...]
system_u:object_r:systemd_unit_file_t:s0  wpa_supplicant.service
unconfined_u:object_r:user_home_t:s0  xkeysnail.service
system_u:object_r:systemd_unit_file_t:s0  zfs-fuse-scrub.service
[...]
```

The solution is to change the context for the file using `chcon`.

```
chcon -v -u system_u --type=systemd_unit_file_t /usr/lib/systemd/system/xkeysnail.service
```

The next step is to remove the use of `sudo` from the lines in the unit file because of the next error that says:

```
xkeysnail.service: Failed at step EXEC spawning /usr/bin/sudo: Permission denied
```

The unit file is in the system dir, belongs root and its context now has the user portion `system_u`, so no need for `sudo` anymore.

What I did not understand yet is if that changed context will persist over boot. I will check that out now.

Also there is one thing missing that I do not like: In the unit file `~.config/kinto/killdups.sh` and `~.config/kinto/kinto.py` are referenced. When xkeysnail really must run as `root` and `system_u` these files should also be owned by it. Better would be in my opinion if nothing had to run as root and system_u, but just as the for whom is the desktop session.

Looking into `~.config/kinto/killdups.sh` I have the feeling that what it does is a job for `systemd` itself btw.

_all copy & pasting in this post done in mac style with running kinto and xkeysnail while SELinux is in enforcing mode_ :-)

**Comment by prosac** [comment]
Rebootet. The file context persists.

**Comment by RedBearAK** [comment]
@prosac 

>_all copy & pasting in this post done in mac style with running kinto and xkeysnail while SELinux is in enforcing mode :-)_

So you actually have `xkeysnail` doing the keyboard remapping on your system without using `sudo`? 

Do you think this might only work in a system that is using SELinux? Enabled by the context change and change of ownership? Or can something like this be done on non-SELinux systems? 

I thought that `sudo` was absolutely required to get `xkeysnail` to work properly. If that could be done away with then we could stop messing around with the troublesome `limitedadmins` sudoers file and maybe even get Kinto working on distros like antiX and Gentoo where that has been a major problem. 

I will certainly take a look at integrating this in my installer fixes for Fedora. Very interesting stuff.

**Comment by prosac** [comment]
> So you actually have xkeysnail doing the keyboard remapping on your system without using sudo?

yes.

> Do you think this might only work in a system that is using SELinux? Enabled by the context change and change of ownership? Or can something like this be done on non-SELinux systems?

As far as I know system units run as root if not specified differently in the unit file. That is independent from SELinux.

**Comment by prosac** [comment]
Made a quick PR https://github.com/rbreaves/kinto/pull/446/files

**Comment by RedBearAK** [comment]
@prosac @rbreaves 

On the interwebs I read that systemd units run "as root" by default but that it is somehow different when you actually specify "root" as the user/group. 

So I tried changing the `xkeysnail` service file to this (adding User and Group, removing all `sudo`): 

```
[Unit]
Description=xkeysnail

[Service]
User=root
Group=root
Type=simple
KillMode=process
ExecStart=/bin/bash -c '/usr/bin/xhost +SI:localuser:root && /home/kris/.config/kinto/killdups.sh && /usr/local/bin/xkeysnail --quiet --watch /home/kris/.config/kinto/kinto.py'
ExecStop=/bin/bash -c 'pkill -f bin/xkeysnail && exit 0'
Restart=on-failure
RestartSec=3
Environment=DISPLAY=:0

[Install]
WantedBy=graphical.target
```

Restarted the service (after `daemon-reload`), and it seems to work fine without `sudo` anywhere in the file. 

Did I just negate the need for `limitedadmins`? Or just for `sudo` in the service file? Stopping and (re)starting the service via the GUI app still seems to work fine too, after `sudo` was removed. Maybe that's the part that still needs `limitedadmins`? 

The terminal seems to ask for a password either way if I'm not using `sudo` on these commands, and even if I use the commands from `limitedadmins` vertabim (full path): 

```
# /etc/sudoers.d/limitedadmins
%kris ALL=NOPASSWD: /usr/bin/systemctl restart xkeysnail
%kris ALL=NOPASSWD: /usr/bin/systemctl start xkeysnail
%kris ALL=NOPASSWD: /usr/bin/systemctl stop xkeysnail
%kris ALL=NOPASSWD: /usr/bin/systemctl status xkeysnail
%kris ALL=(root) NOPASSWD: /usr/local/bin/logoff.sh
%kris ALL=NOPASSWD: /usr/bin/pkill -f logoff
%kris ALL=NOPASSWD: /usr/bin/pkill -f bin/xkeysnail
%kris ALL=NOPASSWD: /usr/local/bin/xkeysnail /home/kris/.config/kinto/kinto.py
%kris ALL=NOPASSWD: /usr/bin/systemctl is-active --quiet xkeysnail
```

**Comment by rbreaves** [comment]
@prosac I believe I agree w/ most of your points, will need to sit down & look it over still. I’ve been wanting to get rid of the sudo requirement & that ought to be possible by giving the current user access to the dev uinput device. I also don’t like punching holes in security either by elevating a user to an entire input device.. why I opted to elevate the specific xkeysnail process instead.

Probably debatable on which action is/was worse.

**Comment by RedBearAK** [comment]
> I’ve been wanting to get rid of the sudo requirement & that ought to be possible by giving the current user access to the dev uinput device. I also don’t like punching holes in security either by elevating a user to an entire input device.. why I opted to elevate the specific xkeysnail process instead.

So did I do something bad by making the whole systemd service unit run as root?

**Comment by rbreaves** [comment]
@RedBearAK The systemd service was already running on system level and not the user domain level. I've been executing it to run though via sudo and by adding in an exception to allow that specific command to run from the regular user after install by modifying the sudoers file to do so. It has been a bit of an ugly hack imo, but one that was acceptable at the time.

Originally back in the early xmodmap days of Kinto I did not use sudo at all and the systemd service I used was completely local to the user only. I have some tech debt I need to be addressing though so that local configs per user can take place properly. I have no opinion about what changes you may have made, still haven't looked it over yet. I have been having issues with Windows 10 lately that has been preventing me from doing much work in any of the Linux distros.

**Comment by tsujp** [comment]
FWIW I tried both @RedBearAK (let's call it 1) and @rbreaves (let's call it 2) branches and for me:

(1) Works on Fedora 34 with SELinux permissive, does not work with enforcing.
(2) Does not work on Fedora34 with SELinux set to enforcing.

**Comment by RedBearAK** [comment]
Resolved.
