### ISSUE TITLE
PowerToys Run support for cmd + space

### ISSUE THREAD

**Issue by phil-bell** [rbreaves/kinto#459]
**Is your feature request related to a problem? Please describe.**
Platform: Windows 10
Keyboard layout: MacOS 
When Kinto with [Microsoft PowerToys](https://github.com/microsoft/PowerToys), pressing cmd+space opens Windows search instead of PowerToys run. Would be really great if we could choose to remap it on Kinto as it seems not to be possible to change the map of PowerToys Run in PowerToys to the new cmd+space.

**Describe the solution you'd like**
During the setup script allow the user to choose if they want to use Windows Search or PowerToys Run as their cmd+space shortcut.

**Additional context**
I'm happy to try and impliment this for you if you can point me in the direction of where the keymapping for cmd+space is?

**Comment by rbreaves** [comment]
Imo it’s not a good idea to mix remappers as that may make things more complicated, if you plan to remap in Powertoys as well.

Kinto by default uses the default hotkey equivalents for the OS, not 3rd part software. I think PowerToys is useful though & Kinto can certainly be extended to support anything - done best by forking probably.

~\.kinto\kinto.ahk
Look for ^{space}

**Comment by phil-bell** [comment]
Great, thank you for the guidence, I'll make a quick fork to test it out.

**Comment by sonhanguyen** [comment]
@rbreaves it could be useful to make a profile for the default PowerToys shortcuts (PowerToys run and fancy zones). Think when people have those two things installed, which is very common given that PowerToys is an official Microsoft's utility set, they would want to have keys mapped for them instead of the (frankly laggy, still) start menu and window snapping.

 I'm not a daily windows user but if you could point me to how to make a profile I can do it and make a pull request next time I boot into Windows.
