### ISSUE TITLE
Alt + UpArrow types a semicolon

### ISSUE THREAD

**Issue by zkuzmic** [rbreaves/kinto#481]
**Describe the bug**
I just installed kinto on Windows 10 and have it set to emulate an Apple keyboard.

Pressing LeftAlt + UpArrow or  LeftAlt + DownArrow (physical keys, not virtual) results in a semicolon being typed on the screen. The cursor also jumps up or down in the document I'm in. So far, I've seen this happen in VSCode as well as Brave browser.

**Expected behavior**
I was trying to move a line of code up or down in VSCode (shortcut is defined as Alt + UpArrow in settings), and wasn't sure what key was actually mapped to Alt, so I just tried each (ctrl, fn, super) but none of them executed that shortcut. I noticed this behavior in the process.

**Install Type:** Bare Metal
**Distro:** Windows, latest (1.2-8?)
**DE:**
**Branch:** master I assume
**Commit:**

Logs and status if relevant

**Screenshots**

**Additional context**

**Comment by rbreaves** [comment]
Hmmm I’ll have to take a look tomorrow, a semicolon should not be getting typed. The other behavior sounds normal.. that’s just what Cmd-Down/Up does on a Mac afaik. Cursor moves to the top or bottom of a document.

**Comment by HADMARINE** [comment]
Is this still open? I am still experiencing this glitch.  
I'm using Windows 11

**Comment by rbreaves** [comment]
I honestly forgot about this but I will admit, particularly on the linux side, VSCode remaps needs some work Alt based combos are problematic over on Linux due to electron type weirdness of alt sending commands to the drop down menus.

Not sure what the issue, but there is not specific remapping done on the virtual Alt-combo keys. Of course on a Windows layout the physical Alt key is Cmd (Ctrl) more or less.
https://github.com/rbreaves/kinto/blob/master/windows/kinto.ahk#L559

With VSCode it is unfortunately inevitable that you will have to make some unavoidable remaps on the VSCode app level - mostly on the Linux side I believe. I will still accept PRs for specific remaps that can be reliably applied however, I just don't have the time to flesh VSCode out a whole lot more. I will keep this issue ticket open for now though and try to get back to it when I can.

One feature I do want to improve is applying Sublime Text 3 keymaps to VSCode, but beyond that not all Alt based combos on Linux will be fixable unless someone shows the way. Windows I think ought to be a different story though - there really shouldn't be anything that can't be remapped one way or another.

**Comment by HADMARINE** [comment]
Alright, I'll try to find and update you the problem.
By the way, I am so happy to use windows with kinto. You've improved my quality of life. Thank you :)

**Comment by HADMARINE** [comment]
Short Update : Not only vscode, but also all of programs including native windows apps, such as notepad, has same issue.


It is not a vscode custom keymapping issue ( 
https://github.com/rbreaves/kinto/blob/master/windows/kinto.ahk#L559 )

I tried to see the actual inputed keys via key tester (https://en.key-test.ru)
![telegram-cloud-photo-size-5-6053272820915482158-y](https://user-images.githubusercontent.com/46421618/127173153-7923292c-5051-4297-8161-cc4afa4692d2.jpg)

See the input history below the windows logo. The order is right to left.

**Comment by HADMARINE** [comment]
Created PR #551

**Comment by HADMARINE** [comment]
Created PR #552
1. Bugfix of semicolon problem
2. Make behaviour the same with mac on ALT + UpArrow / ALT + DownArrow

Please check the code, I currently implemented the code by dividing if the program is vscode or not.
