### ISSUE TITLE
Super key behaves as control in Kubuntu 20.04 terminal

### ISSUE THREAD

**Issue by diazdc** [rbreaves/kinto#520]
Hello, thank you for developing this program. I've been pouring over the documentation and can't figure out how to get the remapped left super key (1st from spacebar) to work with copy/paste in Konsole and the vscode terminal in Kubuntu 20.04. For example, `super + C` still functions as `control + C` and kills the process instead of copying text. If I try to remap the keyboard shortcut, both konsole and vscode still recognize super key as control. 

Is this the expected behavior, or is there something else I'm missing? As I understand, kinto should remap the 1st key from the spacebar as the super key so that it mimics the copy/paste functionality of a mac terminal session. Any help would be greatly appreciated.

**Comment by rbreaves** [comment]
If you installed it by pressing the 2nd key left of the space then yes that is how it ought to behave. The should not be any sigint issues occurring under any Terminal app unless you remapped it already. VS Code and others that have terminals an be a little more difficult to work with because I can't avoid Ctrl-C on the Cmd-C position, but the physical Ctrl-C key will continue to work under code editors as well.

Unless you provide more specific information I will be closing this issue ticket as I expect this to be an issue with having already remapped some keys in Konsole (I have definitely test Konsole btw so I am pretty sure there is no Ctrl-C issue to be addressed).
