### ISSUE TITLE
manjaro-gnome 19.0.2: setup.py -- im-config command not found

### ISSUE THREAD

**Issue by mlbaquerizo** [rbreaves/kinto#53]
When running setup.py in manjaro-gnome 19.0.2 after first logoff and logon
```
Xbindkeys, and xdotool requirement is installed.
You need to set IBus as the default Input Method for full word-wise support and re-run this installer.

im-config -n ibus

Would you like to run it now? (Will require logoff and logon.)
 (Y/n) y
sh: im-config: command not found


IBus has been set as the default Input Method.
```
A success message is displayed at the end even though `im-config` was not run (since it's not installed).

Should there be a step in `setup.py` to install `im-config`? Or am I good to run install?

**Comment by rbreaves** [comment]
That fix is actually in the dev branch already and I probably should hotfix it in because yea, no reason to not fix it in master. I am not ready to merge dev into master still, sorta just taking a break - kde was really messing with me lol.

Running this though will setup the ibus daemon and then the master branch setup installer will work.
```
ibus-setup
```

**Comment by mlbaquerizo** [comment]
@rbreaves That worked, but it looks like the ibus package also needs to be installed before running `ibus-setup`

**Comment by rbreaves** [comment]
Thank you for that feedback. I will make sure to include the pacman install command for manjaro as well then.

**Comment by rbreaves** [comment]
Closing ticket, fix has been merged into master. https://github.com/rbreaves/kinto/releases/tag/1.0.5-10
