### ISSUE TITLE
Not clear how windows management shortcuts work - specifically up / down

### ISSUE THREAD

**Issue by andyd0** [rbreaves/kinto#543]
Without Kinto, Win + up/down/left/right work. With kinto, only left / right work and seem to do nothing. Does this mean it just requires the mapping?

**Comment by rbreaves** [comment]
Win based shortcuts are a bit of an after thought and no real effort is made to maintain them to be honest. If there is an equivalent to a macOS based shortcut then it is added. If there isn't or conflicting shortcuts then it may be eliminated or ignored. Of course you can add back anything your perceive as missing or useful by editing ~\.kinto\kinto.ahk or ~/.config/kinto/kinto.py, depending on the OS.

Also same situation with Linux, I do not go out of my way to break Windows or Linux OS level shortcuts, but I do try and apply things to line up with macs. While using GUI and Terminal apps this results in a lot of modifier key re-arrangement and a few selective remaps per some applications as well. Just as a reminder while using a GUI based app the modifier keys on the left follow this order left to right, Win, Alt, Ctrl - as far as the OS is concerned. The arrangement simply follows the priority of modifier keys in macOS from least used to most often used as it seems like the only way to think of it.

Windows
1,3,2 - Spacebar - 2,3,1

macOS
3,2,1 - Spacebar - 1,2,3

There are 3rd party tools for macOS that allows for similar Window mapping - but nothing built in so unless that changes I have no plans to go out of my way to include this as it could be perceived as Ctrl-up/down/left/right in some applications and I don't really see the placement of the Win key as being stable due to that. It is an under utilized key in multiple ways - much like how Ctrl tends to go under utilized most of the time under macOS. In practice I treat it as both Win or Ctrl when appropriate.
