### ISSUE TITLE
Windows Terminal (and Terminal Preview) bugs out fatally if I press Ctrl + L

### ISSUE THREAD

**Issue by jonchun** [rbreaves/kinto#556]
**Describe the bug**
Kinto on Windows breaks if I press Ctrl + L inside Windows Terminal(Preview). It clearly takes my entire desktop into a weird/bad state where a modifier key is being held down permanently and i can't type/use the keyboard. I can't use the taskbar icon to suspend/quit Kinto either. The only solution I've found is to log out or restart my computer.

**Expected behavior**
I expect either the terminal screen to clear or for nothing to happen similar to in other terminals

**Install Type:** Bare Metal
**Distro:**  Windows 10
**DE:**  Windows 10
**Branch:** master
**Commit:** Not sure where to run this in Windows

**Comment by jonchun** [comment]
Managed to fix this with
```
#l::Send {Blind}{LCtrl down}l{Ctrl up}  ; Default
```
I would submit a PR with {Blind} added, but I don't actually know why/how it fixes it, just that it fixes it. I'll let the expert make the call on what the correct default here should be.

**Comment by rbreaves** [comment]
I will try and test this tomorrow.

**Comment by jonchun** [comment]
Also worth noting that while I couldn't get out of the bad state without logging out initially, I did manage to find that executing `%homedrive%%homepath%\.kinto\kinto-start.vbs` also resets kinto and brings me back into an operational state.

**Comment by rbreaves** [comment]
Yea.. I imagine a bad state is only possible because of it locking.. otherwise suspending or exiting will always unset all modifiers.

**Comment by rbreaves** [comment]
Finally got around to testing this and I do not see that makes any material difference on my local system any at all.. maybe things have changed so much that this is no longer an issue. Odd things do open with Win+L is pressed on the terminal app.. but Win+L in general should not work due to it being reserved by the system.. can even conflict with Ctrl-L due to the way things are layered.

Closing, but will open a new ticket for hopefully resolving the Win-L reserved issue.
