### ISSUE TITLE
Disable ctrl remap in jetbrains products (ideavim)

### ISSUE THREAD

**Issue by tomskopek** [rbreaves/kinto#571]
Ideally, I'd like to keep Ctrl as Ctrl in Webstorm, exactly how it is in terminal. I use ideavim, and have a bunch of keybindings set to use Ctrl. Standard vim keybindings also don't work, for example: Ctrl+u / Ctrl+d for scrolling up/down.
Alt seems to have replaced Ctrl in Webstorm.

I tried adding these two to the IntelliJ section, but it didn't work:

```python
# Keybindings for IntelliJ                                                                                                   
define_keymap(re.compile("^jetbrains-(?!.*toolbox).*$", re.IGNORECASE),{                                                     
     Key.LEFT_CTRL: Key.LEFT_CTRL,
     K("C"): pass_through_key, 
     ...
```

Thank you so much for this repo! I'm still tweaking it but it's a game changer for switching between my mac and linux setup.

**Comment by rbreaves** [comment]
It's going to be more complicated than that most likely - modmaps need to happen under line 103 or 138 and in your case I think a 3rd category would need to be created - I keep things relatively simple though because as far as I am concerned there's only 2 types of apps in terms of modifiers, GUI or Terminal.

What you are wanting in contrast is GUI, Terminal, and Jetbrains in terms of modifiers.

Think of your keyboard like this (some keyboards on laptops lack a mod key on the right).

Mod1, Mod2, Mod3, Spacebar, Mod3, Mod2, Mod1

GUI = Win, Alt, Ctrl, Spacebar, Ctrl, Alt, Win
Term = Ctrl, Alt, Ctrl+Shift, Spacebar, Ctrl+Shift, Alt, Ctrl

What you want on jetbrains only is this I think - unless you want Win to be near the spacebar.
Jetbrains = Ctrl, Alt, Ctrl, Spacebar, Ctrl, Alt, Ctrl

You can do this but you would need to update the logic in kinto.py to also exclude jetbrains along with the terminal and then only apply the modmap modification you want to a new modmap definition set just for Jetbrains. Pretty sure it will not belong in the same "define_keymap(re.compile("^jetbrains-(?!.*toolbox).*$", re.IGNORECASE),{"  line you were modifying and I am not entirely sure of what or how many keymap changes you would then need to make as those remaps assume you have the Win key available.

If you change the modifier key just for Jetbrains then a lot of those remaps following will break as it expects the Win key to be there somewhere. You might be better off bettter understanding how Kinto is operating and change accordingly than to try and change the modifier key remap imo. Better to have 3 unique hotkeys on both sides of the spacebar than 2 imo & terminals are a unique case that often use the shift key so was fairly easy to devise a fix for.

https://github.com/rbreaves/kinto/blob/master/linux/kinto.py
```
define_conditional_modmap(lambda wm_class: wm_class.casefold() not in terminals,{
```

**Comment by rbreaves** [comment]
@tomskopek 

Also it is python.. so may be you can just add an if statement inside the function on line 103 containing the regex

re.compile("^jetbrains-(?!.*toolbox).*$", re.IGNORECASE) and invert it so that the Win key is only remapped if it is not Jetbrains? Maybe you that would let you avoid creating a 3rd category.

**Comment by tomskopek** [comment]
Thanks for the prompt and detailed response @rbreaves
I'm away for the weekend with only my macbook, but I will play with this some more when I'm back in front of linux next week.

**Comment by tomskopek** [comment]
I think I got this working pretty well now, thanks to your help @rbreaves :pray: 

For anyone else wanting to use ideavim:

As noted above, we do in fact want:
GUI = Win, Alt, Ctrl, Spacebar, Ctrl, Alt, Win
Term = Ctrl, Alt, Ctrl+Shift, Spacebar, Ctrl+Shift, Alt, Ctrl
Jetbrains = Ctrl, Alt, Ctrl, Spacebar, Ctrl, Alt, Ctrl

These are the steps I took:

1. in kinto.py, on line 28, created a new array with one member:

```python
jetbrains=["jetbrains-webstorm"] # note that the regex doesn't work here, but I only use webstorm so this worked for me
```

2. change Global modmap on [line 103](https://github.com/rbreaves/kinto/blob/master/linux/kinto.py#L103) to exclude jetbrains

```python
define_conditional_modmap(lambda wm_class: wm_class.casefold() not in (terminals+jetbrains),{
```

3. create a new modmap for jetbrains that copies the one for termStr. in my case:

```python
define_conditional_modmap(re.compile("^jetbrains-(?!.*toolbox).*$", re.IGNORECASE), {                                     
    Key.LEFT_ALT: Key.RIGHT_CTRL,   # WinMac                                                                              
    Key.LEFT_META: Key.LEFT_ALT,    # WinMac                                                                              
    Key.LEFT_CTRL: Key.LEFT_CTRL,   # WinMac                                                                              
    Key.RIGHT_ALT: Key.RIGHT_CTRL,  # WinMac - Multi-language (Remove)                                                    
    Key.RIGHT_META: Key.RIGHT_ALT,  # WinMac - Multi-language (Remove)                                                    
    Key.RIGHT_CTRL: Key.LEFT_CTRL,  # WinMac - Multi-language (Remove)                                                    
})  
```

4. So far I didn't have to tweak anything in the define_keymap block ([line 175](https://github.com/rbreaves/kinto/blob/master/linux/kinto.py#L175)), but since I'm using ideavim for most editing/navigation, that's normal. One thing I did have to add in my ~/.ideavimrc was this: (I sometimes use cmd+f on mac). YMMV

```vim
nmap <c-f> :action FindInPath<CR>
```

Thanks again!
