### ISSUE TITLE
Does not work using UTM on M1 Mac

### ISSUE THREAD

**Issue by kkors** [rbreaves/kinto#573]
**Describe the bug**
I'm running UTM on my M1 MacBook to write code in Ubuntu.
Sadly the keyboard is not mapped correctly so special characters will not appear.
I tried installing kinto to remap the keyboard but nothing changed.

UTM Version 2.2.4
UTM is using a QEMU 6.1 ARM Virtual Machine
There are no keyboard remapping options on UTM

Currently I'm on commit 2a920d0622c1d87873fab12f98ce62b5a9c072d5 on the master branch of kinto.

**Comment by rbreaves** [comment]
I don't currently have an M1 mac or type of mac to conduct tests with - but as a stop gap perhaps remove the latest release and try the earlier release which is based on xkb instead of intercepting physical keyboard devices. I am not sure how UTM works, but it may work better with this release https://github.com/rbreaves/kinto/releases/tag/1.0.7-3.

That release may lack some remaps that the latest release has - and I will admit is harder to add custom remaps to compared to the current releases, but it might work.

If you really want the current release to work though then I would first suggest installing and running xkeysnail more directly and see if it even runs correctly. https://github.com/mooz/xkeysnail

**Comment by rbreaves** [comment]
If this thread is of any indication.. the way UTM captures keyboard inputs needs to be improved or redone so that it capture key presses properly.

https://github.com/utmapp/UTM/issues/2486

My advice might be to install xRDP, and/or NoMachine for Linux, assuming it can compile and run ok on Ubuntu ARM & use RDP for Windows when using Kinto. Those solutions or technologies ought to be capable of fully capturing your keyboard input - even if the UTM client is unable to do so.

Closing this ticket as I believe this to be an issue with UTM & how it handles keyboard input and not Kinto.
