### ISSUE TITLE
Control key does not work as expected when releasing

### ISSUE THREAD

**Issue by jyling** [rbreaves/kinto#623]
**Describe the bug**
Just installed the kinto and noticed one really weird bug when I need to trigger window key with control key, when I first press the key, it trigger the correct one, but it trigger the control key again when I release it, if I hold the control key long enough the window key will be trigger. 

currently set my keyboard type to windows

**Expected behavior**
control key will only trigger window

**Install Type:** Bare Metal
**Distro:** N/A
**DE:** N/A
**OS:** Windows
**Branch:** master
**Commit:** 896ab30e5702cae6710072e9104e3484036d7a1b

**Screenshots**
https://user-images.githubusercontent.com/11886327/153741497-8f1890a5-1c93-4bd1-aa51-dd3d77359bf8.mp4

**Additional context**

**Comment by rbreaves** [comment]
Line 308 in ~\.kinto\kinto.ahk

```
; Hack to disable start menu on winkey
```

The behavior I believe is intentional - will review the video later, not playing back right on my phone. There are other ways to disable the win key but they often disable it entirely & I’m not going to get into the business of re-implementing win key combos after disabling them completely.

I selectively disable just the win key by itself on both Windows & Linux but make little to no attempt at disabling things further.

A string of characters can be added to the registry & explorer.exes restarted to disable selective win key combos as well. I only disable the letter B though.

```
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
"DisabledHotkeys"="B"
```

**Comment by jyling** [comment]
Alright thanks!!!
