### ISSUE TITLE
Question - will this work under nixos + KDE plasma?

### ISSUE THREAD

**Issue by hedefalk** [rbreaves/kinto#63]
Hi,

sorry to post question as issue, but I'm wonder if I could use this for my nixos + KDE Plasma setup?

Coming from MacOS I started remapping everything within KDE but then struck a wall with chromium and FF. Just the simple stuff like cmd-c, cmd-v and such. So started google bonanza and struck this repo.

The readme states "Fedora/RHEL/Manjaro/Arch/Debian/Ubuntu based distro 16.04+" so I guess nixos isn't supported…?

**Comment by rbreaves** [comment]
I believe it can be supported, assuming it uses systemd & the setup.py file is updated to support the Nixos package manager & you install the needed packages.

KDE is equally supported alongside the other DEs in master, but the dev branch has a few more Mac like hotkeys in it mainly for gnome & xfce. KDE hotkeys in dev have not been fully resolved (App switching via Cmd+tab doesn’t behave right).

**Comment by rbreaves** [comment]
If NixOS is anything like Arch you may find it difficult to fully setup IBus to work properly. I still do not know what packages may be missing to allow for Manjaro with Gnome to fully work. There is a panel extension that needs to exist with the IBus input method. If it does not exist then it is not possible to fully remap FF and chrome to behave like it does on macOS because the wordwise hotkeys and the back and forward hotkeys will conflict with each other.

But in theory Kinto should work just fine with any Linux distro, it could even be made to work without systemd easily enough by using the older init or whatever other startup method the distro uses.

**Comment by rbreaves** [comment]
Going to close this ticket, I don't plan on adding anything specific to the installer for this OS, but if anyone wants to modify the installer they are welcome to it and I will accept the PR.
