### ISSUE TITLE
no back or forward on Edge/Linux/Macbook

### ISSUE THREAD

**Issue by Stooovie** [rbreaves/kinto#659]
I love Kinto and it works very well for me on Linux (Pop!_OS) running on a 2015 retina Macbook Pro, BUT I'm unable to go back and forward in MS Edge. It should be Alt-left/right arrows but no key combo works for me. Tried both my native Czech layout as well as the default US English.

Any tips? Thanks!

**Comment by RedBearAK** [comment]
@Stooovie @rbreaves 

Hmm, there is a bit of confusion here because the Windows shortcuts for this in Edge are Alt+Left/Right, but the macOS shortcuts appear to be Cmd+Braces, which matches most other web browsers and file browsers. Looks like the macOS version of Edge also supports Cmd+Left/Right, but the Linux version uses Alt+Left/Right like Windows. That's to be expected. 

Be aware that continuing to use Cmd+Left/Right in Linux for this function may conflict with the "wordwise" shortcuts when you are using Edge. Kinto/xkeysnail doesn't have a smart way to know when the cursor is in a "text area", so the function of the wordwise shortcuts is always active in every application unless overridden. 

```
    # Wordwise
    K("RC-Left"): K("Home"),                      # Beginning of Line
    K("RC-Shift-Left"): K("Shift-Home"),          # Select all to Beginning of Line
    K("RC-Right"): K("End"),                      # End of Line
    K("RC-Shift-Right"): K("Shift-End"),          # Select all to End of Line
```

I would highly recommend training yourself to use Cmd+Braces (the square brackets, which also do tab navigation with Cmd+Shift+Braces) instead, but either can be made to work. 

You're using a real Apple keyboard, so this would be how it would work. The physical Command key is Ctrl with Kinto's remapping of the modifier keys. So remapping Ctrl+Left/Right onto Alt+Left/Right in the config file should enable that. And remapping Ctrl+Braces onto Alt+Left/Right should enable the back/forward navigation with the physical equivalent of Cmd+Braces. 

If you place this code block between the `chromeStr` and `browserStr` blocks found in `~/.config/kinto/kinto.py` and then restart Kinto from the GUI app or tray icon, you should find these shortcuts activated in Edge. 

```
define_keymap(re.compile("microsoft-edge*", re.IGNORECASE),{
    # K("RC-Left"):           K("M-Left"),        # Page nav: Back to prior page in history (conflict with wordwise)
    # K("RC-Right"):          K("M-Right"),       # Page nav: Forward to next page in history (conflict with wordwise)
    K("RC-Left_Brace"):     K("M-Left"),        # Page nav: Back to prior page in history
    K("RC-Right_Brace"):    K("M-Right"),       # Page nav: Forward to next page in history
}, "Browsers")
# Opera C-F12
```

The Ctrl+Left and Ctrl+Right will **_definitely_** block the usage of Cmd+Left (Home) and Cmd+Right (End) functions when editing text in Edge, so I disabled them with the hash/pound symbol. Just remove the hash symbols if you really want to enable those shortcuts. I use the wordwise shortcuts frequently so I would never enable them. 

This is what it would look like in context: 

```
...
define_keymap(re.compile(chromeStr, re.IGNORECASE),{
    K("C-comma"): [K("M-e"), K("s"),K("Enter")],
}, "Browsers")
# Opera C-F12

define_keymap(re.compile("microsoft-edge*", re.IGNORECASE),{
    # K("RC-Left"):           K("M-Left"),        # Page nav: Back to prior page in history (conflict with wordwise)
    # K("RC-Right"):          K("M-Right"),       # Page nav: Forward to next page in history (conflict with wordwise)
    K("RC-Left_Brace"):     K("M-Left"),        # Page nav: Back to prior page in history
    K("RC-Right_Brace"):    K("M-Right"),       # Page nav: Forward to next page in history
}, "Browsers")
# Opera C-F12

# Keybindings for General Web Browsers
define_keymap(re.compile(browserStr, re.IGNORECASE),{
    K("RC-Q"): K("RC-Q"),           # Close all browsers Instances
    K("M-RC-I"): K("RC-Shift-I"),   # Dev tools
...
```

**Comment by RedBearAK** [comment]
@Stooovie @rbreaves 

Actually, as I suspected, it looks like this needs to be fixed for all Chrome(s), not just Edge. I'll be putting together a PR. Tried Google Chrome and Chromium on Linux and they all seem to want Alt+Left/Right for back/forward page history navigation. 

I guess I really don't use Chrome(s) much on Linux, or I would have fixed this a long time ago. 

Confirmed that both Cmd+Braces and Cmd+Left/Right are working shortcuts for this on the macOS version of Google Chrome, just like the macOS version of Edge. Should be the same with Chromium and other Chrome-based browsers. 

This will be the proposed PR: 

```
define_keymap(re.compile(chromeStr, re.IGNORECASE),{
    K("C-comma"): [K("M-e"), K("s"),K("Enter")],    # Open preferences
    K("RC-q"):              K("M-F4"),              # Quit Chrome(s) browsers with Cmd+Q
    # K("RC-Left"):           K("M-Left"),            # Page nav: Back to prior page in history (conflict with wordwise)
    # K("RC-Right"):          K("M-Right"),           # Page nav: Forward to next page in history (conflict with wordwise)
    K("RC-Left_Brace"):     K("M-Left"),            # Page nav: Back to prior page in history
    K("RC-Right_Brace"):    K("M-Right"),           # Page nav: Forward to next page in history
}, "Chrome Browsers")
# Opera C-F12
```

**Comment by RedBearAK** [comment]
@Stooovie @rbreaves 

PR #662 should take care of this on Linux.

**Comment by rbreaves** [comment]
Done. Thanks @RedBearAK

**Comment by rbreaves** [comment]
Although Cmd-Left/Right does collide with wordwise.. not the biggest thing in a browser vs a code editor - but still something that I need to resolve again at some point.

**Comment by RedBearAK** [comment]
> Done. Thanks @RedBearAK

@rbreaves 

Yep, and I think PR #649 should also make this work for Windows browsers. Although I was mostly paying attention to the fact that it didn't work in Firefox when I put that together, it's mapping to Alt+Left/Right which should be the shortcut in Chrome(s), so I'm assuming it should work in all of the Chrome browsers as well. If you merge that it should bring Windows into parity with Linux on this.

**Comment by Stooovie** [comment]
@RedBearAK yes I am aware that on other systems the shortcut is cmd(or whatever) plus braces but that didn't work either. I couldn't go back or forward with any key combo while Kinto was running. 

Thank you for your time!

**Comment by RedBearAK** [comment]
> on other systems the shortcut is cmd(or whatever) plus braces but that didn't work either. I couldn't go back or forward with any key combo while Kinto was running.

@Stooovie 

Yeah, I noticed that while testing. 

I figured out why even trying to use the remapped "Alt" key didn't work. It's due to this block just below the "General GUI" block, containing some other wordwise shortcuts. 

```
define_keymap(lambda wm_class: wm_class.casefold() not in mscodes,{
    # Wordwise remaining - for Everything but VS Code
    K("M-Left"): K("C-Left"),               # Left of Word
    K("M-Shift-Left"): K("C-Shift-Left"),   # Select Left of Word
    K("M-Right"): K("C-Right"),             # Right of Word
    K("M-Shift-Right"): K("C-Shift-Right"), # Select Right of Word
    K("M-Shift-g"): K("C-Shift-g"),         # View source control
...
```

This contains the macOS Option+Left/Right wordwise shortcuts that let you move from word to word with the arrow keys. So in place of Alt+Left it was sending Ctrl+Left to the browser, and (before the fix) there would have been nothing on the keyboard capable of actually sending Alt+Left while Kinto was active. That's why neither Cmd+Left/Right or Cmd+Braces were doing anything for you in Edge. 

Luckily the fix was able to bypass that, as long as you're willing to use Cmd+Braces, or if you want to enable the Ctrl+Left/Right lines and forgo the Home/End shortcuts while using Chrome(s). Up to the user. 

Thanks for bringing this up, I'm surprised I didn't notice it and do a fix a long time ago. Shows how much I've stuck with Firefox while using Linux, and studiously avoided all the Chrome(s). Strangely this was never a problem in Firefox. 

Funny thing is that mapping Cmd+Braces to Alt+Left/Right for back/forward is one of the things I implemented for all Linux file managers in my "Finder Mods". And I did that quite a few months ago. Nice to have this related issue tied up finally.

**Comment by Stooovie** [comment]
Just chiming in to say it works as expected, thank you for such a swift response!
