### ISSUE TITLE
Is it possible for `alt & win` switch for external keyboard?

### ISSUE THREAD

**Issue by cgxxv** [rbreaves/kinto#675]
The question is I'm using a macbook, I want to make the external keyboard work like the internal keyboard. So is it possible for `win & alt` switch in external keyboard?

**Comment by rbreaves** [comment]
Depends on the OS but yes - Windows needs sharpkeys (the file is included but needs to be ran manually). Linux needs keytables to remap usb keyboards - pre kinto, so that Kinto can treat normal usb keyboards as Apple keyboards.

https://gist.github.com/rbreaves/da3bef57a03e4d38d53cea2d46b6ab9e

No immediate plans to integrate this further with Kinto - I think most users would not care to have this feature or if they do it is relatively minor to get it setup and working.
