### ISSUE TITLE
Is there a way to turn off Cmd + mouse scroll to zoom?

### ISSUE THREAD

**Issue by steakscience** [rbreaves/kinto#683]
Hi!

Is there a way to turn off Cmd + mouse scroll up/down to zoom in and out in certain apps (ie. Chrome)?

**Comment by joshgoebel** [comment]
You've have to route your mouse thru xkeysnail and if you did you could add a combo that sent those events to the trash when Chrome was active... I'm not sure I'd recommend that though - mouse events are a lot of traffic, but you could always try it and see.

@rbreaves Should support here extend to helping people modify their xkeysnail configs?

**Comment by RedBearAK** [comment]
@steakscience @joshgoebel 

I feel like this is kind of up to the app, whether they support changing from scrolling to some kind of "zoom" action when Ctrl is held. 

For Chrome there are extensions like "Disable Ctrl + Scroll Wheel Zoom" that should be able to disable this within that specific app. 

In Firefox you should be able to go to `about:config` and: 

>Double-click the **mousewheel.with_control.action** preference and edit the value from 3 (zoom) to 1 (scroll), then click OK 

I don't think this really has much to do with Kinto since the same behavior works on similar Mac apps when you hold Cmd, and the solutions would generally be the same. Disabling the behavior in the app, if there is a way to do so.

**Comment by joshgoebel** [comment]
Disabling the behavior in the app, if there is a way to do so.

> That's probably better than adding a mouse to the keymapper ONLY to ignore it selectively.

**Comment by steakscience** [comment]
Thank you @joshgoebel @RedBearAK !
