### ISSUE TITLE
Ubuntu 22.04 Support

### ISSUE THREAD

**Issue by timkofu** [rbreaves/kinto#740]
**Is your feature request related to a problem? Please describe.**
Kinto is not installing on Ubuntu 22.04. It Fails with the following message:
```
Failed to get session path: Caller does not belong to any known session.
You are not using x11, please logout and back in using x11/Xorg
```

**Describe the solution you'd like**
For Kinto to install successfully on Ubuntu 22.04.

**Describe alternatives you've considered**
Manually mapping keys using `gnome-tweaks`.

**Additional context**
Thanks for making this handy tool.

**Comment by rbreaves** [comment]
Closing. Known issue related to Wayland, not specific to 22.04.

Also a duplicate as I know we've got other threads discussing wayland quite a bit, plus that's what the error message is talking about when it says you are not using x11, the only supported option atm. The readme also mentions it.

**Comment by timkofu** [comment]
Thanks. Found issue #699 which linkes to your superuser post.

**Comment by rbreaves** [comment]
Yea - that superuser post is really, really old. Kinto has gone through a rewrite since then and uses xkeysnail vs a custom c app I wrote. Also Kinto is about to be switched over to a fork of xkeysnail as well. If wayland gets figured out with the fork though then kinto will benefit from that, more likely to happen there than with xkeysnail at this point.

https://github.com/rbreaves/kinto/issues/447
