### ISSUE TITLE
Can it be disabled for specific applications?

### ISSUE THREAD

**Issue by npearson72** [rbreaves/kinto#8]
First of all, thank you for this great tool!

My issue is that I use TMUX and all my mappings in my config are set to Alt (or Meta), and since this key is swapped, I get conflicts in terminal under certain conditions.

I'm wondering if I can disable kinto just for terminal but keep it running for all other applications?

**Comment by rbreaves** [comment]
```
vi ~/.config/xactive.sh
```
and change this line
```
swapcmd_term="setxkbmap -option;setxkbmap -option altwin:swap_alt_win"
```
to just
```
swapcmd_term="setxkbmap -option"
```
That should default it back to normal and for me it sets the option to us by default, but you can also add any 2 character initial after option for whatever language you want.

I don't think I will be adding that feature to the installer, unless I start adding a lot of additional configurations - but I feel like that may be outside the scope of what I am aiming to do with Kinto, which is just to bring a macOS keyboard feel to any Linux distro.

And thank you, I am glad that you and others appear to be appreciating Kinto! :)

**Comment by rbreaves** [comment]
Also just to note, I am a definite fan of tmux, but since I take my queues primarily from macOS's key layout I don't have that particular issue with my config files.

I was curious though if there is a way to have tmux run a command or script to toggle the Kinto keymap on or off, and it looks like it may be possible. One of the comments in this thread, I'm linking below, mentions a FocusIn hook that you could try using if you want to be more specific about disabling or enabling the terminal based keymap.

https://github.com/mawww/kakoune/issues/2406

**Comment by npearson72** [comment]
@rbreaves thanks for the tip. That seems to have gotten me partially there. The `Alt` button works as needed and my TMUX configs are running smoothly.

However, my Command/Windows key is now mapped as `Ctrl` and my `Ctrl` is mapped as `Super`. Is there a way to swap those (just in terminal)?

**Comment by npearson72** [comment]
Seems I figured it out. I changed that line to:

```
swapcmd_term="setxkbmap -option;xkbcomp -w0 -I$HOME/.xkb ~/.xkb/keymap/kbd.chromebook.gui $DISPLAY; setxkbmap -device $usbid -option altwi
n:ctrl_alt_win"
```
That makes my windows/command key = super, while alt is alt and ctrl is ctrl.

I hope I'm not breaking anything by doing this.

**Comment by rbreaves** [comment]
I am a little surprised that the command key would be mapped as Ctrl after running "setxkbmap -option". Whether the Apple driver is loaded or not I would have expected Command to be mapped as either the Super key or the Alt key depending on whether the Apple driver is loaded or not.

Also that is fine, if the chromebook file resolves the issue for you. I would think that specifying "-device $usbid" is not needed though. The only time making use of $usbid or $internalid is useful is when you are trying to ensure that both a laptop and external keyboard are mapped properly at the same time, otherwise one may map correctly and the other not, in my experience and most often when involving chromebooks.

I'd be curious to know the results of the following.

```
lsmod | grep hid_apple
```
If the Apple hid driver is loaded then read the output of the swap file
```
cat /sys/module/hid_apple/parameters/swap_opt_cmd
```
If it isn't set to 1 then I'd make sure to set it so it aligns with a typical windows keyboard. I prefer to do things this way because if or when you swap out keyboards then the same keymaps should apply to other windows based keyboards as well.
```
echo '1' | sudo tee -a /sys/module/hid_apple/parameters/swap_opt_cmd
```

If the Apple driver isn't being made use of then typically the mac_only portion of the script should go into effect, which has a very specific keymap for gui and term. If the chromebook.gui file seems to work for you though then that is fine, it makes use of an option called "chromebook(swap_lalt_lctrl)" which can probably be set other ways as well, aka

```
swapcmd_term="setxkbmap -option;setxkbmap -option ctrl:swap_lalt_lctl"
```
Not sure if you need to tack on "setxkbmap -device $usbid -option altwi
n:ctrl_alt_win" like you had been doing or not.

I am a little surprised that chromebook xkb types would even be available to be honest, I assumed that was specific to GalliumOS and possibly other Linux specific distros for chromebooks.

**Comment by npearson72** [comment]
That is interesting. Not sure why it's working then. At first I tried using the following:

`setxkbmap -option;setxkbmap -option ctrl:swap_lwin_lctl; xkbcomp -w0 -i $internalid -I$HOME/.xkb ~/.xkb/keymap/kbd.chromebook.gui $DISPLAY`

I was just going by the argument naming `ctrl:swap_lwin_lctl` as that seemed close to the issue I was having, so I was curious what would happen. No change with this so I kept poking around and just by chance landed on:

`setxkbmap -option;xkbcomp -w0 -I$HOME/.xkb ~/.xkb/keymap/kbd.chromebook.gui $DISPLAY; setxkbmap -device $usbid -option altwin:ctrl_alt_win`

My actual problem was just that `Alt` and `Win` needed to be swapped. `Ctrl` was working fine.

Here's the output to the commands you requested:

```
nathan@redman:~$ lsmod | grep hid_apple
nathan@redman:~$ cat /sys/module/hid_apple/parameters/swap_opt_cmd
cat: /sys/module/hid_apple/parameters/swap_opt_cmd: No such file or directory
nathan@redman:~$ echo '1' | sudo tee -a /sys/module/hid_apple/parameters/swap_opt_cmd
[sudo] password for nathan:         
tee: /sys/module/hid_apple/parameters/swap_opt_cmd: No such file or directory
1
```

I should probably mention that I'm currently trying this in a VB running Linux Mint (cinnamon) on a Mac. Not sure if that info helps at all.

**Comment by npearson72** [comment]
BTW.. I did swap in your suggestion:

`swapcmd_term="setxkbmap -option;setxkbmap -option ctrl:swap_lalt_lctl"`

This works!

**Comment by npearson72** [comment]
@rbreaves So I did a fresh re-install of Linux Mint and tried your original suggestion:

`swapcmd_term="setxkbmap -option"`

That seems to work now. Maybe I had tinkered with some other setting before that interfered with it. Anyway, all great now. I'm closing this ticket.
