### ISSUE TITLE
Windows (regular keyboard)

### ISSUE THREAD

**Issue by IgnacioAgustinCabral** [rbreaves/kinto#851]
Is there a way to use my Logitech keyboard (it has the Win key) as the Mac keyboard on Ubuntu 22.04?

If this has already been addressed please refer me to it

**Comment by RedBearAK** [comment]
@IgnacioAgustinCabral 

(I'm not the Kinto dev, just a minor contributor.)

> Is there a way to use my Logitech keyboard (it has the Win key) as the Mac keyboard on Ubuntu 22.04?

Have you tried installing Kinto? And setting the keyboard type in the tray icon menu to "Windows"? That's normally all you need to do in order to make Windows-style keyboards behave like an Apple keyboard.

**Comment by rbreaves** [comment]
You may want to refer to this post here as MX keyboards may have detection issues. I do not recall if I ever addressed it or not, more of a xkeysnail issue than Kinto - but of course it impacts Kinto if it impacts xkeysnail since Kinto does run off of a fork of xkeysnail.

Closing this for now - as I have no current plans to dig deeper. Of course I will accept PR's to either Kinto or my fork of xkeysnail rather if anyone wants to make a proper fix - although the fix that that user applied to xkeysnail I could actually port as is most likely.  Sadly I do not think they ever submitted it as a PR.

https://github.com/rbreaves/kinto/issues/617#issuecomment-1025900901
