### ISSUE TITLE
Language switch doesn't work in Ubuntu default terminal

### ISSUE THREAD

**Issue by sokolegg** [rbreaves/kinto#882]
Hey, thanks for your project, it works well but on 
Ubuntu 24
I can't switch language in ubuntu terminal (Russian language)

**Comment by RedBearAK** [comment]
@sokolegg 

What physical keys are you using for this? 

If you're mimicking macOS, it would be physical `Ctrl+Space`. In non-terminal GUI apps that will be logical `Super+Space`, because that's where the Meta/Super/Win modifier gets moved. But in terminals the `Super` key disappears and becomes `LC` (`LEFT_CTRL` to distinguish from the virtualized `Cmd` key that's actually `RIGHT_CTRL`). That would cause the shortcut to not work in terminals. 

So you may need to remap `LC-Space` and `Shift-LC-Space` back to `Super-Space` and `Shift-Super-Space` in the general terminals keymap. Which is at the very end of Kinto's default config file. 

```py
    K("LC-Space"):       K("Super-Space"),
    K("Shift-LC-Space"): K("Shift-Super-Space"),
```

If those aren't the keys you're using, you'll have to specify the keys and the native shortcut(s) needed for the input switching.

**Comment by sokolegg** [comment]
Thanks for your help, 
Yes I want to switch it via Ctrl+Space

Where is default terminals keymap? in kinto.py?
You have there few different maps, what should I use?

**Comment by RedBearAK** [comment]
The keymap at the end of the `kinto.py` config file should do the job. It's just tagged with the name "terminals". 

Add the remaps from earlier, save the file and restart Kinto to see if it works. 

https://github.com/rbreaves/kinto/blob/4a3bfe79e2578dd85cb6ff2ebc5505f758c64ab6/linux/kinto.py#L785-L846
