### ISSUE TITLE
Can't refuse to view one-time initialization tweaks

### ISSUE THREAD

**Issue by Jonchun** [rbreaves/kinto#90]
**Describe the bug**
When the installer asks "One time initialization tweaks are available. Would you like to view them? (Y/n)", you can't refuse it. Hitting "n" proceeds to show you the tweak settings.

**Expected behavior**
I would expect it to exit the installer immediately. Or perhaps I'm misinterpreting the installer...

**Install Type:** Bare Metal
**Distro:** KDE Neon
**DE:** KDE
**Branch:** master

**Comment by rbreaves** [comment]
I think you a misinterperting the installer. It does skip the one time init options from a quick test I did, but the dynamic tweak shortcuts are different (even though the 2 seem related at this time because it deals with unbinding the overlay/activities overview key and rebinding). 

I really have not fleshed out all of the possible dynamic tweak shortcuts, but to be honest I do not really have to under Gnome, and even KDE or xfce to some degree. It all depends on whether or not the DE allows for multiple keybindings to be assigned to the same action. If not then the dynamic keybinding options can become more important as it will be the only real way to maintain parity with mac like shortcuts while using the terminal or a gui based app.

The dev branch is mostly trying to accomplish the mac shortcuts by modifying the default DE shortcuts to accept multiple keybinds any time we're dealing with Ctrl vs Ctrl+Shift (aka Cmd). It works well most of the time, but app switching is odd because Shift is expected to reverse the cycle and I can't really do that while you are using the terminal.

**Comment by Jonchun** [comment]
Got it -- This issue should definitely be closed then.

> I can unmap the always on Shift key specifically on Tab while the terminal apps are in use, but then I can't re-apply Shift if you were to actually press Shift. App cycling on the Terminal apps is a bit of a no win situation - if it treated Left vs Right shift individually I could work it out, but xkb doesn't.
Ah, I see the problem here. Thankfully, I personally have never used cmd+shift+tab because it's generally more ergonomic to hit cmd+tab multiple times (I hit tab with my pinky) so it works out either way haha

**Comment by rbreaves** [comment]
Looking at these two files would sorta tell you want you need to know. You'd need to follow the level order from mac_term though, not mac_gui type file. So that'd be type "ONE_LEVEL_CMD" in mac_term.

Key thing is to use clearmods to clear a modifier key and use modifiers to set a different modifier (if you need to set another one at all - in many cases you don't). Also whether an app will respect/recognize the modifiers set by xkb is anyone's guess - most do, but not all as I have found out in KDE's Task Switcher.

In the below example you'd swap out
```
NoAction(), // second one
```
with
```
RedirectKey(key=<AC01>,clearmods=Shift),
```

https://github.com/rbreaves/kinto/blob/dev/.xkb/symbols/mac_gui
```
...
    // Ctrl + A - Beginning of Line
    replace key <AC01> {
        type[Group1]= "ONE_LEVEL_SUPER",
        symbols[Group1]= [
            // Base
            a,
            // Shift
            A,
            // Super
            NoSymbol,
            // Shift Super
            NoSymbol
        ],
        actions[Group1]= [
            NoAction(),
            NoAction(),
            RedirectKey(key=<HOME>,clearmods=Super),
            RedirectKey(key=<HOME>,clearmods=Super)
        ]
    };
...
```

https://github.com/rbreaves/kinto/blob/dev/.xkb/types/mac_gui

**Comment by Jonchun** [comment]
That's very helpful! I've gone a bit insane and spent way too much time on a new repo (even more insane than my previous one...) 
https://github.com/Jonchun/macify-linux

**Comment by rbreaves** [comment]
On your fork I'd just create another branch with your own custom keymap additions. If you do that then I'd think it'd be easy enough to merge my existing master and dev branches into the same branches on your fork and then merge those into your custom branch.

It is more steps and it can seem like a bit of work if you're not using git as frequently as what I do/have, but I'd think that'd make it a little easier to manage. It'll only get hairy if you have to resolve some merge conflicts.

And I do apologize that my xkb keymap symbols files are not as clear or well documented as I like, a lot of it I was figuring out as I went a long, but any new additions I have made are documented a little better as I am trying to keep sanity as well.

I am now labeling groups and should be doing actions as well with stuff like "// Base", "// Shift", "// Ctrl" and "// Ctrl Shift" so it is much clearer to myself and new comers what the hell that file is actually doing - because unless you really understand xkb and are following how the files are all linking up it is not obvious what is going on at all.
