### ISSUE TITLE
Switch keyboard layout

### ISSUE THREAD

**Issue by Huligan4j** [rbreaves/kinto#91]
Hello, how can I change the keyboard layout from us to ru on capslock? When I install kinto everything works except switching the layout.
If possible, could you post a full guide.
Thanks.

**Comment by rbreaves** [comment]
Now this is the type of multi-language support question I can help with! And from what I am reading online this is also how macOS handles toggling language keyboard layouts (or it can any ways via the capslock key).

So for now you'll need to do a couple of things manually until I make it part of the installer.
```
# Make note of the original setting, if anything, as a backup
gsettings get org.gnome.desktop.wm.keybindings switch-input-source

# Set the input to VoidSymbol
gsettings set org.gnome.desktop.wm.keybindings switch-input-source "['VoidSymbol']"
```

Pull down the latest master branch and reinstall Kinto, this will give you the latest mac_gui symbols file.

Now edit the two keymap files with the new symbols option "+mac_gui(caps_none)"
~/.xkb/keymap/kbd.mac.gui
```
...
	xkb_symbols   { include "pc+us+pl:2+us:3+inet(evdev)+ctrl(swap_lwin_lctl)+ctrl(swap_rwin_rctl)+mac_gui(caps_none)+ma...
```
Do the same on the term file
~/.xkb/keymap/kbd.mac.term

Now toggle between a gui app and terminal and the settings should be taking effect there after. The capslock key will now only switch between keyboard languages you've configured.

If you have any questions let me know, but I will be closing this ticket.

**Comment by Huligan4j** [comment]
I use xfce4, changed mac_gui (mac_levelssym) to mac_gui (caps_none) and added the latest changes to .xkb / symbols / mac_gui, but nothing works anyway
What could be the problem?

**Comment by rbreaves** [comment]
The DE won't have any impact on the keymap file and I am not sure what you mean by "changed mac_gui (mac_levelssym) to mac_gui (caps_none)" because you're not replacing "mac_gui (mac_levelssym)". All that you are doing really is adding "+mac_gui(caps_none)" somewhere inside the xkb_symbols entry on the files in the keymap directory.

Sorry if that wasn't clear before. Just make sure you apply to both ~/.xkb/keymap/kbd.mac.gui & ~/.xkb/keymap/kbd.mac.term files and from there it should begin to work just fine. The Kinto installer takes care of the symbols file, so there really isn't anything for you to do manually there.

~/.xkb/keymap/kbd.mac.gui
~/.xkb/keymap/kbd.mac.term
Just make sure you add to add "+mac_gui(caps_none)" somewhere inside the double quotes of ' include "" '
```
xkb_symbols   { include "" }
```

Everything should just work after that.
