### ISSUE TITLE
support italian keyboard apple/windows (3 chars on key)

### ISSUE THREAD

**Issue by zofe** [rbreaves/kinto#94]
**Is your feature request related to a problem? Please describe.**
on ubuntu 18.04  italian, this was the setup:
2. mac type, 1. mac hid driver, 1 gnome-init  (default, blank for all others)

on a italian layout, there are four keys with 3 chars mapped:
+*]
èé[  
òç@   
à°# 

without kinto the second char is mapped  on "shift + {key}"  
without kinto the third char is mapped on "cmd + {key}"  or "AltGr + {key}"  (respectively on apple or windows keyboard)

after kinto setup  I'm not able to  type the third char for each key:    ] , [ , @ , # 

**Describe the solution you'd like**
keep same combination for keys  with 3 chars mapped:
"cmd + {key}" and "AltGr + {key}"  should be always mapped on the third char if key is used for 3 chars in current keyboard layout (this should be true for italian layout but also other languages)

**Describe alternatives you've considered**
describe where fo find configuration to remap  third char if key is used for 3 chars

**Comment by rbreaves** [comment]
Sounds like I need to figure out which "Mod" key name is associated with AltGr and add that to the xkb types files. I believe that'll return that functionality.. I am a little surprised that it would have disappeared still.

**Comment by sebgiles** [comment]
I would like to report the same problem, additionally the uninstall script did not put things back and I still have no AltGr, how can I reset this? Thank you in advance

**Comment by rbreaves** [comment]
Please be more specific on saying did not put things back. The script should be capable of resetting to defaults just fine, nothing special about gnome, KDE or xfce. Also it’s possible that you could need to log off & back on to feel the changes. AltGr should be restored after that if not already I’d imagine. The changes that Kinto makes is very shallow in that they’re all user level & not very extensive at all, making them easy to undo.

**Comment by sebgiles** [comment]
Hi, thanks for getting back to me so quickly.
After running uninstall and rebooting I still have the following:

1. Right Alt is acting as Super instead of Alt
2. Right command is acting as AltGr instead of Super

I can probably figure out a way of fixing it myself, but if you could suggest the "right way" I'd be grateful as it would be probably cleaner. 

Running uninstall again yields:
```
~/.../kinto(master)$ ./uninstall.sh 
Failed to disable unit: Unit file keyswap.service does not exist.
Failed to disable unit: Unit file keyswap.timer does not exist.
rm: cannot remove '/home/seb/.config/systemd/user/keyswap.service': No such file or directory
rm: cannot remove '/home/seb/.config/systemd/user/keyswap.timer': No such file or directory
```

I'll add that I originally uninstalled because it completely froze both USB mouse and keyboard, and kept doing so within 5 seconds of every reboot, I had to run the uninstall script via ssh from my laptop, maybe that is the reason?
My keyboard is an Apple Magic Keyboard with numeric Keypad, which I am connecting over USB-Lightning cable.

**Comment by rbreaves** [comment]
Oh, I know what it is that the uninstall script is not undoing now. Thanks for the clearer description of the issue.

I need to add this line to the uninstall script.
```
echo "options hid_apple swap_opt_cmd=0" | sudo tee -a /etc/modprobe.d/hid_apple.conf
update-initramfs -u -k all
```

The reason for it to swap that key is that it helps to make the keyboard align with Windows style keyboards and if someone wants to swap out keyboards for whatever reason it helps with that, so they don't need to reinstall Kinto. Otherwise the Mac Only and macbook VM keymap is recommended.

In the next few days I am probably going to release a new update to Kinto that uses udev (xkeysnail). It is already in the alpha branch and tested to be functional on both Ubuntu and KDE Neon. Perhaps it will be more stable for you, I don't know why your usb mouse and keyboard would freeze, first time I have heard about that.

It makes sense for it to occur 5 seconds into the reboot, that is when Kinto is to startup, there is a delayed start that is intended to ensure that x11 is ready for kintox11, otherwise it will fail and need to restart until it succeeds. It really shouldn't freeze things up though - I have tested this in several distros and DE's and the only one that gave me issues initially was KDE Neon, but afaik I got those worked out with @jonchun. And I really do like KDE Neon so it was important to get that working.

If you want to give me more information about your setup I will make sure it is part of my testing, but I will likely be moving on to focusing my efforts on the udev/xkeysnail remaps and not xkb/kintox11 going forward. xkb could be causing the instability, it seems like there may be minor version differences out there between distros and it is difficult to know how they can impact things. Even minor differences in systemd as well.

Moving over to udev I think provides a platform that is likely less riddled with OS/DE differences since it occurs on a lower level and will likely bring additional app support, particularly for remote desktop apps.

**Comment by sebgiles** [comment]
Running those two lines fixed it thanks (the second also wanted sudo)
My setup is quite simple at the moment as it's a two days old install of Ubuntu 18.04. I'm going to try again now.

**Comment by sebgiles** [comment]
Unfortunately it froze again. 
It's just Ubuntu 18.04 with the standard GNOME. The computer is an HP Z230 Workstation, but that shouldn't matter. [ShellTile](https://extensions.gnome.org/extension/657/shelltile/) is the only Gnome 
extension I installed.

**Comment by rbreaves** [comment]
So @jonchun just got back with me on testing the new xkeysnail method and apparently I left out a critical line that probably needs to run before you run the xkeysnail service if you try out the alpha branch.. Running it manually though should be fine.

```
xhost +SI:localuser:root

sudo systemctl restart xkeysnail
```

**Comment by nicobargit** [comment]
I runned in the same issue, do you have a workaround?

**Comment by rbreaves** [comment]
@nicobargit I'd suggest that you checkout the alpha branch and see if the ./xkeysnail_service.sh installer may work for you (it will disable the xkb kinto service during install). That is where the active development is taking place at this time I have no eta for when the xkb version of kinto may or will be updated to resolve this particular issue.

To resolve the issue a modification of some kind would need to occur in the mac_term/mac_gui files under the .xkb/symbols and types folders. It can be resolved, but it just isn't the highest priority item - and the newer udev/xkeysnail method likely won't have this issue at all, although I have not tested it under other languages than english either.

**Comment by rbreaves** [comment]
I am not sure that this is still an issue. I know changes in the install script have occurred to help with keeping AltG r in its original location vs its relocation as well as updating the uninstaller. Also made recent changes to make a reinstall on top of itself (if one changes to Mac only) to undo the official Apple keyboard keyswap as well on the driver level.

If it is an issue still just follow up with me and I will reopen it.

**Comment by zofe** [comment]
It's working great now

**Comment by Ale-quad** [comment]
Hi rbreaves,

thank you for your amazing work. I have been a Mac user for ages, and I had to build a workstation for rendering purposes, which feels like home with Kinto. 

However I have changed my previous US apple wired keyboard, with an Apple wireless italian layout one. Since then I am having the issues as described in this post, in which the ò keystroke does not provide the @ with the left Option as it should. If I press LCtrl+Option+ò, I can get the @ but then the keyboard would freeze as one of these modifier is kept pressed.

In addition Kinto started to switch automatically to "windows keyboard mode" even if autodetect keyboard is deactivated.
Any help woudl be greatly appreciated, thank you again!
